### PR TITLE
refactor(plugins) removing unused parameter in auth plugins

### PR DESCRIPTION
**Pull request by thefosk**

### CODE REVIEW

**Comment by Tieske** [comment]
Not sure about this. I see the parameters always being `nil`, but that said, I like the explicitness that is conveyed as in "we're NOT passing headers here".

Maybe others have opinions. @thibaultcha @p0pr0ck5 @bungle

**Comment by p0pr0ck5** [comment]
If we're trying to keep the function signature identical and verbose, it would make sense to define the third parameter as `nil`, rather than removing it all together.

That being said, it seems like there is some code duplication across these handlers; I wonder if some of that can be targeted for a refactor as well.

**Comment by thibaultcha** [comment]
Not sure since when we started passing explicit `nil` to optional arguments as an idiom in Lua? Anyways.

**Comment by bungle** [comment]
Is this fourth parameter here intentional:
https://github.com/Mashape/kong/blob/next/kong/plugins/aws-lambda/handler.lua#L108

**Comment by bungle** [comment]
Currently there are 6 uses for:

```lua
responses.send(err.status, err.message, err.headers)
```

That may not be enough to warrant something like:

```lua
responses.send(err)
-- or
responses.send_error(err)
```

But what do you think?

**Comment by bungle** [comment]
In general I am  "less code / syntax the better" type of person. That may be something I need to unlearn. And only based on that, I would agree here with @thefosk that those should go.

**Comment by p0pr0ck5** [comment]
@bungle looks like that fourth param in the aws-lambda plugin is unused. maybe legacy cruft? looks like the signature changed in commit `ecd76210`.

At any rate, its merged now. :)

**Comment by thibaultcha** [comment]
FYI: the responses module is legacy code and bound to disappear/be rewritten as part of the core/plugins public Lua API of Kong.

**Pull request merged**
