### PR TITLE
Sort request_path_arr by descending specificity

### LINKED ISSUE #1144: find_api_by_request_path incorrectly picks less specific nested route
When the following two API definitions are registered —
```
{name = "mockbin", request_path = "/some/deep", upstream_url = "http://mockbin.com"},
{name = "mockbin", request_path = "/some/deep/url", upstream_url = "http://mockbin.com"}
```
Kong resolves a request to `/some/deep/url` to either of the two since they both satisfy the generated regular expression. 

The API it resolves to will always be the first one in the database's natural order (since the aforementioned function loops through the `request_path_arr` and returns the first match). In case `/some/deep` was registered before `/some/deep/url`, a request to `/some/deep/url` will resolve to `/some/deep` incorrectly. 

@thefosk, this is what I was facing in https://github.com/Mashape/kong/issues/890

### PR DESCRIPTION
**Pull request by siddharthkchatterjee**
@thefosk, fixes #1144

### CODE REVIEW

**Comment by siddharthkchatterjee** [comment]
@thibaultCha, quick question. 

The invalidate function in hooks.lua has the following statements when `collection == "apis"`
```
elseif message_t.collection == "apis" then
  if message_t.entity then
    cache.delete(cache.api_key(message_t.entity.id))
  end
  cache.delete(cache.all_apis_by_dict_key())
```
Isn't the `cache.delete(cache.api_key(message_t.entity.id))` redundant since after that you are deleting `all_apis_by_dict_key` anyway?

The reason I ask is because I need the sorting to take place whenever the cache is invalidated including updating existing apis, for instance if a request_path was updated.

**Comment by thibaultCha** [comment]
You'd have to ask @thefosk for this.

**Comment by thibaultCha** [comment]
Otherwise the sorting sounds like a good idea, and looks good too! I'll give this a try. Thanks for the patch!

**Comment by siddharthkchatterjee** [comment]
@thibaultCha, thank you. Can we make a release with this as soon as possible? Our production stack depends on it.

**Comment by thibaultCha** [comment]
We'll release it once it's thoroughly tested and not before, but more importantly we're not planning on doing any patch release for 0.7 with it right now, only in 0.8, which comes with heavier features that need to be tested too.

If this patch works for you, you can apply it to your setup while waiting for 0.8.

**Comment by siddharthkchatterjee** [comment]
@thibaultCha, alrighty then. We'll wait it out for 0.8 and switch to postgres along with this fix.

**Comment by thefosk** [comment]
@siddharthkchatterjee regarding your question, `cache.all_apis_by_dict_key()` and `cache.api_key(message_t.entity.id)` are two different keys in the cache, so we have to delete both of them.

**Comment by thefosk** [comment]
I have also cherry-picked the commits and merged them into `release/0.8.0`.

**Pull request merged**
