### PR TITLE
tests(acl) reading the response body

### PR DESCRIPTION
**Pull request by thefosk**

### CODE REVIEW

**Comment by Tieske** [comment]
I don't think we should remove this.

The http client requires the body to be read iirc, to be able to make a next request. Hence to prevent future nasty issues due to reuse of the client or by copy-pasta of code I think it should remain as it is.

**Comment by thefosk** [comment]
@Tieske sorry - remove what?

**Comment by Tieske** [comment]
@thefosk the `read_body()` call this PR is about

**Comment by thibaultcha** [comment]
This PR is actually adding the call, as I pointed out to @thefosk yesterday.

**Comment by Tieske** [comment]
lol, sorry for the noise.

**Pull request merged**
