### PR TITLE
hotfix(migrations): set default for anonymous with auth plugins

### PR DESCRIPTION
**Pull request by Tieske**
The default value for `anonymous == ""`, yet the migrations were missing

fixes #2264 but for all auth plugins.

### CODE REVIEW

**Comment by thefosk** [comment]
This adds a new migration, which could possibly break a running cluster, therefore needs to be merged against `next` and not `master.

**Comment by p0pr0ck5** [comment]
@thefosk any way to make an exception here, given that a). this migration is very straightforward, and b). there are issues on 0.10.1 that this will fix? (#2293)

**Comment by thefosk** [comment]
@p0pr0ck5 it depends. What if this operation fails:

```
row.config.anonymous = ""
local _, err = dao.plugins:update(row, { id = row.id })
```

and we have 50% of plugins updated, and the other 50% not updated. How will this affect the cluster? 

In my opinion migrations shouldn't be pushed in minor releases.

**Comment by Tieske** [comment]
> What if this operation fails:

In this case, it doesn't matter, you can run the migration again. That said, a migration takes a different upgrade approach, hence I'm with @thefosk that it should not be in a minor release.

**Comment by p0pr0ck5** [comment]
> That said, a migration takes a different upgrade approach, hence I'm with @thefosk that it should not be in a minor release.

So should we update this PR to target `next` instead of `master`?

**Comment by thefosk** [comment]
> So should we update this PR to target next instead of master?

+1

**Comment by Tieske** [comment]
@p0pr0ck5 @thefosk please check #2313 against `next`

**Pull request closed without merging**
