### PR TITLE
feat(meta) add support for OpenResty 1.11.2.2

### PR DESCRIPTION
**Pull request by thefosk**
### Full changelog

* Add support for OpenResty 1.11.2.2
* [Internal] Updates Serf to 0.8 in tests and Luarocks to 2.4.1.

### CODE REVIEW

**Comment by thibaultcha** [comment]
Proper prefix is: `chore(deps) ...`

**Comment by thefosk** [comment]
Currently a problem with Serf 0.8

**Comment by Tieske** [comment]
@thefosk what's the status on this? `next` and `master` already are on Serf 0.8

**Comment by thibaultcha** [comment]
replaced by #1878.

**Pull request closed without merging**
