### PR TITLE
random failing ci tests with 'address already in use'.

### PR DESCRIPTION
**Pull request by Tieske**
Possible fix by closing server sockets explicitly.

Not sure whether this works as only ci will tell...

### CODE REVIEW

**Comment by Tieske** [comment]
This PR appears to fix the issue with the starting and stopping of the dummy servers. The ones remaining are CLI tests for restarting Kong.

The tests (at runtime in the CLI modules) for the sockets being in use seem invalid. Nginx sets up the sockets with the REUSEADDR option, this is a must to be able to restart a server (see [this link](http://stackoverflow.com/questions/6960219/why-not-using-so-reuseaddr-on-unix-tcp-ip-servers)). Yet the test ([here](https://github.com/Mashape/kong/blob/921a31ec96e483f9ab8cc33df5a725213ab42414/kong/cli/utils/signal.lua#L234-L238) and [here](https://github.com/Mashape/kong/blob/921a31ec96e483f9ab8cc33df5a725213ab42414/kong/cli/utils/utils.lua#L122-L128)) performed doesn't seem to take this REUSEADDR option into account. It just sees the address in use and bails out.

That's my guess, but I don't know the `nc` (netcat) utility well enough.

Can we check, the availability of the socket by creating a server socket (WITH the reuseaddr option) and report success based on that?

pinging @thefosk as the test seems your code.

**Comment by thefosk** [comment]
The error that TravisCI detected is now different, and it belongs to this code: https://github.com/Mashape/kong/blob/master/kong/cli/utils/utils.lua#L125-L128

Basically we are stopping and starting the nginx process subsequently very fast, but it seems like when nginx starts again, the port is still open by the previous process. This could be caused by a few reasons:

* The `is_port_open` check doesn't work
* Although nginx has been stopped, the system still didn't free up that port (maybe to flush existing connections?)

Regarding the first issue which is the original motive for this PR, only executing the Travis build multiple times we will know if it's effectively a fix, or we were just lucky.

**Comment by thefosk** [comment]
@Tieske I agree to change the `is_port_open` function with a different system.

**Comment by thefosk** [comment]
@Tieske On a side note, these two are not the only problems we have with tests (with others impacting the way rate-limiting works, for example). So feel free to ping me whenever a test fails because I may already know what it's happening.

**Comment by Tieske** [comment]
> The error that TravisCI detected is now different, and it belongs to this code:

Yes, saw that. That is the same code I linked to in my previous post.

> - Although nginx has been stopped, the system still didn't free up that port (maybe to flush existing connections?)

That's when the socket is in WAIT_STATE, the OS cannot close it until it times out (part of TCP design), despite the process already being gone. See http://stackoverflow.com/questions/14388706/socket-options-so-reuseaddr-and-so-reuseport-how-do-they-differ-do-they-mean-t

> - The `is_port_open` check doesn't work

It works, but is too simple. Even if an address is in use, if it was set with SO_REUSEADDR (which any restartable server does/should do), another process can still reuse it. So `is_port_open` is reliable, but tells something different than what we need to know, we need `is_port_usable`.

> Regarding the first issue which is the original motive for this PR, only executing the Travis build multiple times we will know if it's effectively a fix, or we were just lucky.

Obviously, but I feel lucky today :smile:

**Comment by thefosk** [comment]
> Yes, saw that. That is the same code I linked to in my previous post.

I think we literally posted the comment one second apart from each other, so I didn't see your response :)

> we need `is_port_usable`

You nailed it. I am following the progress of this PR.

**Comment by thefosk** [comment]
@Tieske any new update on this PR?

**Comment by thefosk** [comment]
On a side note it seems like `reuseport` would be a better fit here, unfortunately currently unsupported in LuaSocket: https://github.com/diegonehab/luasocket/issues/149

**Comment by thibaultCha** [comment]
**Note: to be closed re-opened again the `next` branch (See #622)**

**Comment by Tieske** [comment]
replaced by #777

**Pull request closed without merging**
