### PR TITLE
spec(cli) pending port open test

### PR DESCRIPTION
**Pull request by thibaultCha**
@Tieske this test, correct? if so, let's wait and see how the builds perform on this PR already.

#777

### CODE REVIEW

**Comment by Tieske** [comment]
No, my PR contained the updated test function `is_port_bindable` which I believe is better.

The current `is_port_open` test uses an OS command that checks whether a process is holding on to a socket. That returns `true` even if the socket is abandonned and in `TIME_WAIT` state. We should test by actually trying to bind to the port, which will succeed that specific case.

**Comment by Tieske** [comment]
You can accept my PR and then set the test to pending, that should work.

**Comment by thibaultCha** [comment]
Ok

**Comment by Tieske** [comment]
just as a reference, that would be #777

**Pull request closed without merging**
