### PR TITLE
Issue 594

### PR DESCRIPTION
**Pull request by smanolache**
issue 594:
  added support to kong such that it does not try to process
  the request if a ngx binary module stopped the request processing

### CODE REVIEW

**Comment by thibaultCha** [comment]
Could you re-open this against the `next` branch please?

**Comment by smanolache** [comment]
`ngx.ctx.stop_phases` is never set to `false` in the code. It is just set to `true` when kong wants to stop the processing of the request. So I suppose the test `ngx.ctx.stop_phases == false` is never true.

I have tried checking for `ngx.ctx.stop_phases == false` as you suggested and I've gotten `HTTP/1.1 500 Internal Server Error` and `{"message":"An unexpected error occurred"}` and `[error] 28214#0: *1 invalid URL prefix in "nil"` in the logs.

**Comment by thibaultCha** [comment]
It'd be nice to initialize it when a request is incoming then. I kind of don't like that it's only initialized when we want to stop the processing :/ and it will simplify those statements.

**Comment by smanolache** [comment]
On 2015-11-03 19:00, Thibault Charbonnier wrote:
> It'd be nice to initialize it when a request is incoming then. I kind of
> don't like that it's only initialized when we want to stop the
> processing :/ and it will simplify those statements.

Ok. I'll add "ngx.ctx.stop_phases = false" at the entry of 
exec_plugins_access, change the "ngx.ctx.stop_phases ~= nil and not 
ngx.ctx.stop_phases" to "ngx.ctx.stop_phases == false", and retest.

**Comment by smanolache** [comment]
It's not clear how to add `ngx.ctx.stop_phases = false` because it's not clear which is the first callback that is called.

For example if a binary ngx module returned `unauthorized` in the `access` callback then kong's `access` callback is not called any more and then the first of kong's callbacks to be called is `header_filter`. Otherwise it is kong's `access` callback that is called first. So I cannot just set `ngx.ctx.stop_phases = false` in `header_filter` because maybe it was set to `true` in `access`. And if I set it in `access` then I won't see it in `header_filter` because `access` might not be called. I could write something like
```lua
if ngx.ctx.stop_phases == nil then
   ngx.ctx.stop_phases = false
end
```
both in `access` and `header_filter` but it would be uglier than the current solution.

There's the problem of `plugins_certificate`. Currently, if I'm not mistaken, it does not work, because the `ssl_certificate_by_lua` directive does not work (or at least I couldn't make it work: I could apply the patch to nginx but the support for the configuration directive is missing in ngx_lua-0.9.16). When is it called? When an https request is made by a client to kong or when kong makes an https request to an api? In the first case there's no request so `ngx.ctx.stop_phases` makes no sense while in the second case there's a request and `ngx.ctx.stop_phases` makes sense.

**Comment by thibaultCha** [comment]
(Moved to #679)

**Pull request closed without merging**
