### PR TITLE
[JWT] support for base64 encoded secrets and arbitrary claim for secret

### PR DESCRIPTION
**Pull request by ryanbreen**
This patch adds support for a configurable JWT secret key field,
defaulting to 'iss'.

### CODE REVIEW

**Comment by thibaultCha** [comment]
Nice, thank you!

**Comment by ryanbreen** [comment]
@thibaultCha, I have a follow-up to this patch to add support for Base64-encoded secrets (https://github.com/ryanbreen/kong/pull/1).

If I submit that patch against next, you're going to get some painful merge conflicts since jwt-secret-key-field and jwt-secret-base64 touch a lot of adjacent lines.  It seems cleaner to propose it as a commit extending this branch, so that's what I've done.

How would you prefer to see such a PR proposed?

**Comment by thibaultCha** [comment]
Very nice! Here is good for me as a second commit (with tests)!

**Comment by ryanbreen** [comment]
Cool, merged onto this PR.

As background, Auth0 generates JWTs signed by a key that is a Base64-encoded binary blob (witness the "secret base64 encoded" checkbox at jwt.io). This patch adds support for such secrets while preserving the status quo by default.

I believe this patch is necessary: decoding the secret provided by Base64 and attempting to use it in its raw form is a non-starter: round-tripping it through UTF-8, as would be necessary using `curl` in a terminal to pass these secrets to Kong APIs, will perturb the byte stream and lead to spurious signature mismatches.

**Comment by thibaultCha** [comment]
Thank you for the patch! Very much appreciated. I will review shortly. In the meantime, could you get rid of the merge commit? That'd be great

**Comment by ryanbreen** [comment]
Cool, done.

**Comment by thibaultCha** [comment]
Thank you!

**Pull request merged**
