### PR TITLE
feat(core) upstreams

### PR DESCRIPTION
**Pull request by Tieske**
### Summary

Adds the upstreams feature. A work in progress...

For a basic description see https://github.com/Mashape/kong/issues/157#issuecomment-238205952

### An incomplete todo list;
- [x] implement dns resolver
- [x] implement balancer_by_lua
- [x] resolve SRV records
- [x] implement dns retries
- [x] implement balancer
- [x] implement balancer retry
- [x] implement dns resolution for cli
- [x] implement dns resolution for co-sockets (ldap/cassandra/postgres)
- [ ] tests, tests, and more tests...
- [ ] timestamp millisec precision

For now most of the existing test suite passes.

### CODE REVIEW

**Comment by thefosk** [comment]
> implement balancer_by_lua to replace proxy_pass

`balancer_by_lua` shouldn't replace `proxy_pass`, they should coexist? Maybe it's a typo, just want to make sure we are on the same page.

**Comment by Tieske** [comment]
👍  we're on the same page

**Comment by Tieske** [comment]
**Status so far;**

- tests are now passing (except some plugins, like ldap)
- dns resolver has been implemented (uses https://github.com/Mashape/dns.lua)
- A and SRV records are now loadbalanced by Kong internally
- entities `upstreams` and `targets` have been added to the datastore and management api, but are NOT functional.

**Some questions;**

1. what would need to be configurable?
   - see https://github.com/Mashape/kong/blob/aca3c9000682e8ff6be40af8b90928b79e490423/kong.conf.default#L230-L241
   - see dns-object cache; https://github.com/Mashape/dns.lua/blob/master/src/dns/client.lua#L175-L180
2. what errors to return for failed dns lookups?

**testing;**
I'll try to keep this branch functional. I'll make updates in new branches, and only complete functioning updates will be merged in this branch. So at any given time this branch should be testable.


Any input, on the questions above or test results, is most welcome!

**Comment by Tieske** [comment]
closing this in favor of #1735

**Pull request closed without merging**
