### PR TITLE
Feat/plugin by name on management api endpoint

### PR DESCRIPTION
**Pull request by Tieske**
on `kong:8001/apis/{api_name_or_id}/plugins/{plugin_name_or_id}` the plugin can now be specified by either `id` or `name`.

### CODE REVIEW

**Comment by p0pr0ck5** [comment]
Commit message looks like it needs fixing?

**Comment by Tieske** [comment]
@p0pr0ck5  What did I F-up this time?

**Comment by p0pr0ck5** [comment]
`feat(plugin)`?

**Comment by p0pr0ck5** [comment]
Ahhhhhh, ignore me, i was looking at the PR title. Sorry!

**Comment by Tieske** [comment]
that's the PR title, not the commit message

**Comment by p0pr0ck5** [comment]
Rebased with dc8cc254eaa6fa71f3a42414ef427a2a077beae9

**Comment by thibaultcha** [comment]
iirc, the reason why it was decided that plugins should not be query-able by name was because it can be desired (in the future) to have several instances of a same plugin (with different configurations) on the same entity (consumer/API...). Now that is the historical reason, and because the model is still lagging behind, no such capability was ever added. However, if that is something we are still considering, removing this endpoint will be required and will be a breaking change in the future.

That is just the historical reason behind it. That said, I believe that such a change (new model) would be massive enough that is will probably break other things anyways, and such an endpoint as this PR proposes is nice to have.

In the future, should we also consider implementing `/consumer/{consumer}/{plugin name or id}`? The exception will be `/plugins/{plugin id}` which cannot be modified to receive a name or an id.

**Comment by Tieske** [comment]
> In the future, should we also consider implementing `/consumer/{consumer}/{plugin name or id}`? 

yes

**Pull request merged**
