### PR TITLE
Syslog and Loggly plugins

### PR DESCRIPTION
**Pull request by shashiranjan84**
Syslog Plugin - send logs to local system log
Loggly Plugin - send logs to Loggly over UDP

### CODE REVIEW

**Comment by sinzone** [comment]
why not open two separate PR?

**Comment by shashiranjan84** [comment]
I started with aim to get loggly working but it turn out that we can also another plugin syslog logging to system log. so did both in same branch.

**Comment by shashiranjan84** [comment]
syslog plugin will work with both any 3rd party supporting syslog format like Loggy and SymoLogic

**Comment by thibaultCha** [comment]
Please reopen against `next` as explained in #622.

**Comment by shashiranjan84** [comment]
Oh sorry totally forget about that

**Pull request closed without merging**
