### PR TITLE
fix(admin) disable plugin names in /api/:id/plugins*

### PR DESCRIPTION
**Pull request by kikito**
* Reverts the main part of #2726
* Needs to be merged before #2714 in order to make its tests pass

### CODE REVIEW

**Comment by thibaultcha** [comment]
(Slightly reworked this to better follow the conventions of `crud_helpers.lua`, use the same function on the `plugins.lua` routes, and to update the commit message with some more context)

**Comment by thibaultcha** [comment]
Actually it seems that this change in general - and not my latest additions - broke the invalidations tests, since those rely on the plugin by name feature for now.

**Comment by kikito** [comment]
@thibaultcha I changed the invalidation tests so they didn't rely on the plugin names for the tests. I'm leaving that on a separate commit, hoping it is alright.

**Comment by thibaultcha** [comment]
@kikito I think it's fine if those are part of the same commit. The scope being "disabling feature X", we should not leave the state of the repo in a non-working state after the related commit is done (harder to detect changes with `bisect`). Instead, if we remove feature X, we should also update tests relying on feature X at the same time, so that once the commit applied, the repo's tests are left in a working state. I'll be squashing them, no worries!

**Pull request merged**
