### PR TITLE
fixes issue #949 , single commit

### LINKED ISSUE #949: Kong start error in Ubuntu 15
kongerror

Above error appears when we try to start the kong instance, configured cassandra in same machine changed/enabled the configuration in kong.yml to refer local cassandra instance.

### PR DESCRIPTION
**Pull request by ajayk**
Closes #949.

### CODE REVIEW

**Comment by thibaultCha** [comment]
Sounds good :+1:

I will apply the patch manually with minor modifications and probably add a test case. Thanks you!

**Comment by ajayk** [comment]
@thibaultCha : if the spec_helpers.get_env could return an malformed / invalid yml file , i can add the test cases

**Comment by thibaultCha** [comment]
I believe [start_spec](https://github.com/Mashape/kong/blob/master/spec/integration/cli/cmds/start_spec.lua) shoule have such a test, and mess up with the configuration syntax somehow.

**Comment by Tieske** [comment]
I think the error message returned by the yaml lib should also be appended to the log message to give some clues about what was wrong and where.

did a quick test, generating an error with these `pcall` results;
````
Mashapes-MacBook-Pro:Code thijs$ lua yaml-test.lua
false	did not find expected '-' indicator at document: 1, line: 4, column: 1
while parsing a block collection at line: 2, column: 1

Mashapes-MacBook-Pro:Code thijs$ 
````
Appending that error message will give a better clue to the user about what was wrong.

**Comment by thibaultCha** [comment]
It's part of the changes I wanted to add manually yes. Feel free to add it @ajayk

**Comment by thefosk** [comment]
@ajayk updates?

**Comment by ajayk** [comment]
@thefosk pushing it today !

**Comment by thibaultCha** [comment]
Thank you for your contribution!

**Comment by thibaultCha** [comment]
I applied the patch manually to `next`. Closing this now :)

**Comment by ajayk** [comment]
@thibaultCha i will put the error message in the next commit , thanks for closing this !

**Pull request closed without merging**
