### PR TITLE
Ldoc

### LINKED ISSUE #498: Add documentation
I'd like to add inline documentation to the codebase, preferably using [ldoc](https://github.com/stevedonovan/LDoc). Ldoc is pretty much the Lua standard for documentation.

I find the code pretty terse, so while going through it, it might be worthwhile to document my findings for future benefit of others.

### PR DESCRIPTION
**Pull request by Tieske**
closes #498 

Adds ldoc configuration and updated comments.

### CODE REVIEW

**Comment by thibaultCha** [comment]
Sounds good. I'm not sure we need the config.ld file though?

**Comment by Tieske** [comment]
It allows writing `ldoc .` on the command line to generate the docs. Instead of specifying a bunch of options everytime. I added some comments to that file with explanation and instructions.

**Comment by thibaultCha** [comment]
I know ldoc, I'm just not sure the generation part is necessary.

**Comment by thibaultCha** [comment]
It might actually confuse people when visiting/cloning the repo and seeing a "config" file but not understanding how it is related to Kong or Kong's config. Not a lot of people are familiar with Lua.

**Pull request merged**
