### PR TITLE
Make oauth2 tests pass

### PR DESCRIPTION
**Pull request by scottefein**
This is a super mundane fix to make the OAuth2 plugin pass. Looks like there was a change to the error description.

### CODE REVIEW

**Comment by Tieske** [comment]
changes have already been committed through #798 thanks for the effort anyway :+1: 


(minor nit; next time please send a PR against the `next` branch)

**Comment by scottefein** [comment]
@Tieske Could you update the Contributing guidelines to reflect the next branch? https://github.com/Mashape/kong/blob/master/CONTRIBUTING.md

**Comment by thibaultCha** [comment]
It is in there

> If all went well, we are eager to see your contribution, feel free to submit your Pull Request against the next branch.

And for hotfixes:

> If the fix is urgent, feel free to open the PR against the master branch.

**Comment by Tieske** [comment]
just updated CONTRIBUTING.md to make it a bit clearer.

**Pull request closed without merging**
