### PR TITLE
Added JWTAuth plugin

### PR DESCRIPTION
**Pull request by jasonmotylinski-dowjones**
We have the need to verify JWT tokens coming in through Kong. Most of the code in pull request is based on work done by jerizm (https://github.com/jerizm/kong.git). The code was updated to support base64 encoded secrets for compatibility with Auth0.com.

### CODE REVIEW

**Comment by sinzone** [comment]
Just heads up.. this week we're focused in releasing the 0.4 and updating docs. Next week we'll review this PR and merge.

**Comment by jasonmotylinski-dowjones** [comment]
FWIW - This code utilizes luajwt which only supports HMAC-based algorithms. It may be worth looking into lua-resty-jwt for RS256 support.

**Comment by thefosk** [comment]
@jasonmotylinski-dowjones do you think it's worth using lua-resty-jwt since day one, in order to support all the other algorithms?

**Comment by jasonmotylinski-dowjones** [comment]
Yeah, it does make sense to switch now. I thought I'd get away with just HS256 at my company but they told me that RS256 is what they want to support. I'll update this pull request with lua-resty-jwt.

**Comment by sinzone** [comment]
great! we'll wait for the review then.

**Comment by jerizm** [comment]
:+1:  Awesome I'll go ahead and close my pull request.

**Comment by sinzone** [comment]
@jasonmotylinski-dowjones for the docs part, pls open a PR on this repo (the site): https://github.com/Mashape/getkong.org (you can follow the same structure we use in other plugins)

for the plugin logo we'll take care of it.

**Comment by thefosk** [comment]
I can help with the docs, as soon as this PR is complete (with lua-resty-jwt).

**Comment by thefosk** [comment]
@jasonmotylinski-dowjones - do you believe this is still something you can do, or you want me to jump in?

**Comment by jasonmotylinski-dowjones** [comment]
Feel free to jump in. I've been pulled away from it.

On Wednesday, August 12, 2015, Marco Palladino <notifications@github.com>
wrote:

> @jasonmotylinski-dowjones <https://github.com/jasonmotylinski-dowjones> -
> do you believe this is still something you can do, or you want me to jump
> in?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mashape/kong/pull/404#issuecomment-130507469>.
>


-- 
Jason Motylinski
Head of Data Engineering

612.752.1113 tel
651.208.2870 mobile
*jason.motylinski@dowjones.com <jason.motylinski@dowjones.com>*

**Comment by thibaultCha** [comment]
This cannot be merged anymore since the history rewrite, closing it to make sure.

**Comment by thefosk** [comment]
Just to leave an update on this, I will still take this code as the starting point for the JWT plugin.

**Comment by sinzone** [comment]
do we have the an issue somewhere?

**Comment by dvh** [comment]
According to the wiki this should be part of the 0.0.5 release. I can't find it in the milestones however. Is this still planned to be supported soon?

**Comment by sinzone** [comment]
https://stormpath.com/blog/build-secure-user-interfaces-using-jwts/

**Comment by sinzone** [comment]
@Tieske can you pls take a look at this one?

**Comment by Tieske** [comment]
I'll look into it. Just to make sure we're on the same page here, the intent is to use [lua-resty-jwt](https://github.com/SkyLothar/lua-resty-jwt). Correct?

**Comment by sinzone** [comment]
yes

**Comment by thefosk** [comment]
@Tieske yep, in order to support `HS256`, `HS512` and `RS256`

**Pull request closed without merging**
