### PR TITLE
fix(conf) drop lua_code_cache option

### PR DESCRIPTION
**Pull request by Tieske**
This option no longer works, but triggers a lot of support
questions.

### CODE REVIEW

**Comment by thibaultcha** [comment]
Before merging this, I would be very much inclined to reproduce the errors (it should be fairly easy to reproduce), and keep track of them somewhere.

**Comment by thibaultcha** [comment]
Spent some time on there, and init_worker not being run when lua_code_cache is false is our issue. A lot of modules initialized in init_worker should be initialized in init instead, but cannot because of lua-resty-worker-events iirc.

Regardless, considering the implications of disabling this directive and how limiting it is (lack of ngx.semaphore, FFI contexts, and the number of lua-resty modules depending on them), it might indeed be better to simply drop support for it, I concur.

**Comment by Tieske** [comment]
> Before merging this, I would be very much inclined to reproduce the errors (it should be fairly easy to reproduce), and keep track of them somewhere.

@thibaultcha I didn't fully understand what you meant by this? considering your follow up message, it it good to merge now? if not please elaborate on what you meant by the above.

**Comment by thibaultcha** [comment]
@Tieske I meant to spawn a lua_code_cache disabled instance and see how it behave. While I very much like the idea of an instance on which developers can freely edit it without having the reload Kong, I think the trouble of maintaining such a convenience isn't worth the currently needed refactor  nor the potential limitations we could encounter in the future...

I say: merge!

**Pull request merged**
