### PR TITLE
Update README URLs based on HTTP redirects

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Created with https://github.com/dkhamsing/frankenstein

### CODE REVIEW

**Comment by ahmadnassri** [comment]
thank you, can you please keep the HTTPS urls for getkong.orh

**Comment by ReadmeCritic** [comment]
Hm ok

**Comment by ReadmeCritic** [comment]
@ahmadnassri updated

**Comment by thibaultCha** [comment]
Manually merged to both next and master, thanks!

**Pull request closed without merging**
