### PR TITLE
tests(admin) fix active targets api test flakiness

### PR DESCRIPTION
**Pull request by bungle**
### Summary

Fixes flaky test (ordering of inserted APIs could get mixed and cause test to fail)

### CODE REVIEW

**Comment by p0pr0ck5** [comment]
I'm not quite sure about this. I'm not sure the original comment was quite valid; does this suite actually use C* in the first place? If not, I don't think the fix here, based on a faulty assumption, is valid.

**Comment by thibaultcha** [comment]
Correct, the comment isn't true. However, @bungle's finding related to this part: https://github.com/Mashape/kong/blob/master/kong/api/routes/upstreams.lua#L138-L151

@bungle says that if several targets are created under the same ms, the all share the same `created_at`, then the `table.sort` function will base its choice on the UUID part of the sorting key. Then, L.149 and 150, if the first target in the loop has `weight == 0`, then it will be marked as `seen` and will obfuscate subsequent targets even if they have `weight > 0`. They were created later-on, but still too close to the previous target to be distinguished from it.

**Comment by thibaultcha** [comment]
(The long term fix seems to also lie in a better way to ensure that this edge-case doesn't happen at all. A more deterministic sorting algorithm? Or load balancing structure altogether.)

**Comment by bungle** [comment]
Correct.

This: https://github.com/Mashape/kong/blob/master/kong/api/routes/upstreams.lua#L137-L142

will result different results on each test run on fast machines because the APIs are created with same time. Then next sorting criteria is UUID which is used as a sorting criteria, and with good luck you get UUIDs that sort exactly the way they are inserted here:

https://github.com/Mashape/kong/blob/master/spec/02-integration/04-admin_api/08-targets_routes_spec.lua#L292-L301

On my machine it more often fails than I get lucky. With really slow machines, the `created_at` will always be different, and the test will then of course work.

**Comment by bungle** [comment]
@p0pr0ck5, and yes the fix is not based on that faulty comment. If it was, the sleep would be in different place. E.g. in the actual test (it tried that as well before I figured out the real reason).

**Comment by bungle** [comment]
@thibaultcha, I agree adding sleeps to fix tests is not the longterm solution. This fixes the flakiness, not the root of the problem, which is a bit harder one to fix.

**Comment by thibaultcha** [comment]
> I guess that having the test running is more important than the fix the root of the problem for now.

We fully agree on that! I was just trying to highlight to @p0pr0ck5 that we were not dismissing the importance of a proper, more robust fix :)

**Comment by p0pr0ck5** [comment]
> Then next sorting criteria is UUID, and with good luck you get UUIDs that sort exactly the way they are inserted here:

Yes, I had this exact same discussion with Tieske several months ago: https://github.com/Mashape/kong/pull/2230#discussion_r107515014. I still don't understanding his reasoning.

> This is usually not a real-world problem, so I guess that having the test running is more important than the fix the root of the problem for now.

Hmmm, I would have to say I would disagree here. If the test is running but passing, it obscures the buggy behavior in the actual code. Putting a band-aid on the test is only likely to make us forget this exists? But, at the end of the day it really isn't a big deal :)

**Comment by thibaultcha** [comment]
> But, at the end of the day it really isn't a big deal :)

This is also the conclusion reached at the end of your discussion on that PR. Additionally, this test *is* relevant in the sense that it ensures the endpoint is functioning and the sort order is deterministic (undefined in some edge-cases, but still deterministic). I'm :+1: on this PR.

**Comment by bungle** [comment]
@p0pr0ck5 maybe we should add another test that shows up this particular edge case, but in a way that it always shows it. Not like in current form where on slow machines it might now show up.

**Comment by thibaultcha** [comment]
I consider the scope of this PR reached and beneficial to the tests suite, so let's merge this.

@bungle I think that is a good idea - or create an issue to keep track of this behavior could help as well!

**Pull request merged**
