### PR TITLE
docs: add a 'Getting Started' section to README

### PR DESCRIPTION
**Pull request by thibaultCha**
Add a "Getting Started" section to the README (could later be moved to getkong.org). It describes adding an API, querying it, adding a plugin (authentication), and re-querying the API.

Writing this raised some concerns:

- The API routes do not feel RESTful #98
- It feels weird to be able to create empty accounts #96 
- headerauth and queryauth should probably be the same plugin #95
- it's a lot of stuff to configure...

@thefosk @montanaflynn @Nijikokun @sinzone Feel free to comment or checkout and improve. Here is a copy-pasta:

## Getting started

Kong will look by default for a configuration file at `/etc/kong/kong.yml`. Make sure to copy the provided `kong.yml` there and edit it to let Kong access your Cassandra cluster.

Let's start Kong:

```bash
$ kong start
```

This should have run the migrations to prepare your Cassandra keyspace, and you should see a success message if Kong has started.

Kong listens on these ports:
- `:8000`: requests proxying
- `:8001`: Kong's configuration API by which you can add APIs and accounts

#### Hello World: Proxying your first API

Let's add [mockbin](http://mockbin.com/) as an API:

```bash
$ curl -i -X POST \
  --url http://localhost:8001/apis/ \
  --data 'name=mockbin&target_url=http://mockbin.com/&public_dns=mockbin.com'
HTTP/1.1 201 Created
...
```

And query it through Kong:

```bash
$ curl -i -X GET \
  --url http://localhost:8000/ \
  --header 'Host: mockbin.com'
HTTP/1.1 200 OK
...
```

#### Accounts and plugins

One of Kong's core principle is its extensibility through [plugins](http://getkong.org/plugins/), which allow you to add features to your APIs.

Let's configure the **headerauth** plugin to add authentication to your API. Make sure it is in the `plugins_available` property of your configuration.

```bash
# Make sure the api_id parameter matches the one of mockbin created earlier
$ curl -i -X POST \
  --url http://localhost:8001/plugins/ \
  --data 'name=headerauth&api_id=<api_id>&value.header_names=apikey'
HTTP/1.1 201 Created
...
```

If we make the same request again:

```bash
$ curl -i -X GET \
  --url http://localhost:8000/ \
  --header 'Host: mockbin.com'
HTTP/1.1 403 Forbidden
...
{"message":"Your authentication credentials are invalid"}
```

To authenticate against your API, you now need to create an account associated with an application. An application links an account and an API.

```bash
$ curl -i -X POST \ 
  --url http://localhost:8001/accounts/
  --data ''
HTTP/1.1 201 Created
...

# Make sure the given account_id matches the freshly created account
$ curl -i -X POST \
  --url http://localhost:8001/applications/
  --data 'public_key=123456&account_id=<account_id>'
HTTP/1.1 201 Created
...
```

That application (which has "123456" as an API key) can now consume authenticated APIs such as the previously configured mockbin:

```bash
$ curl -i -X GET \
  --url http://localhost:8000/ \
  --header 'Host: mockbin.com' \
  --header 'apikey: 123456'
HTTP/1.1 200 OK
...
```

To go further into mastering Kong, refer to the complete [documentation](#documentation).

### CODE REVIEW

**Comment by Nijikokun** [comment]
Needs a bit of TLC in the paragraphs (Tender loving care)

**Comment by thibaultCha** [comment]
1. valid point
2. 3. I explained in the comments every time.
4. My philosophy was to not enter too deep into details here and rather link to "more docs" at the end of the tutorial. Also in the future this parameter should have a default
5. Depends on where luarocks is installed. More work needed to automatically put it to `/etc/kong` (Leverage luarocks if possible, or Makefile (breaks the "luarocks-only" install) or rely on OS package managers (thus would not work out of the box for luarocks installs)
6. valid point
7. valid point

Thanks

**Comment by Nijikokun** [comment]
2. & 3. didn't read the comments, didn't jump out at me, easy to gloss over

4. less of automatically, but more of here is a generic cp function replace this path with where it exists to place it under `/etc/kong`

**Comment by thibaultCha** [comment]
Note to self: example of what `plugins_available` should look like in the configuration.

**Comment by thibaultCha** [comment]
New version then, a little bit verbose:

[diff between first proposed version and this one](https://github.com/Mashape/kong/compare/b1ca12f878b9f6242390bb0eb13a673ad4c80c1d...9ac646fe4731d0303e34a221e5cfd1b0a596c14d)
- Sample:

## Getting started

Kong will look by default for a configuration file at `/etc/kong/kong.yml`. If you installed Kong from luarocks, you can copy the default configuration from the luarocks tree (`luarocks --help` to print it). Usually:

```bash
cp /usr/local/lib/luarocks/rocks/kong/<kong_version>/conf/kong.yml /etc/kong/kong.yml
```

Edit the configuration to let Kong access your Cassandra cluster.

Let's start Kong:

```bash
$ kong start
```

This should have run the migrations to prepare your Cassandra keyspace, and you should see a success message if Kong has started.

Kong listens on these ports:
- `:8000`: requests proxying
- `:8001`: Kong's configuration API by which you can add APIs and accounts

#### Hello World: Proxying your first API

Let's add [mockbin](http://mockbin.com/) as an API:

```bash
$ curl -i -X POST \
  --url http://localhost:8001/apis/ \
  --data 'name=mockbin&target_url=http://mockbin.com/&public_dns=mockbin.com'
HTTP/1.1 201 Created
```

We used the `8001` port, the one of the configuration API.

And query it through Kong, by using the `8000` port, the one actually proxying requests:

```bash
$ curl -i -X GET \
  --url http://localhost:8000/ \
  --header 'Host: mockbin.com'
HTTP/1.1 200 OK
```

Kong just forwareded our request to `target_url` of mockbin and sent us the response.

#### Accounts and plugins

One of Kong's core principle is its extensibility through [plugins](http://getkong.org/plugins/), which allow you to add features to your APIs.

Let's configure the [headerauth](http://getkong.org/plugins/header-authentication/) plugin to add authentication to your API.

###### 1. Enable the plugin

Make sure it is in the `plugins_available` property of your node's configuration:

```yaml
plugins_available:
  - headerauth
```

This will make Kong load the plugin. If the plugin was not previously marked as available, restart Kong:

```bash
$ kong restart
```

Repeat this step for every node in your cluster.

###### 2. Configure the plugin for an API

To enable this plugin on an API, retrieve the API `id` (as the one of the freshly created mockbin API) and perform a `POST` request with the following parameters:

> **name**: name of the plugin to create a configuration for.
> **api_id**: `id` of the API this plugin will be added to.
> **value.header_names**: `value` is a property of every plugin, representing their configuration. `header_names` will here be a list of headers in which users can pass their API key.

```bash
$ curl -i -X POST \
  --url http://localhost:8001/plugins/ \
  --data 'name=headerauth&api_id=<api_id>&value.header_names=apikey'
HTTP/1.1 201 Created
...
{
  "api_id": "<api_id>",
  "value": { "header_names":["apikey"], "hide_credentials":false },
  "id": "<id>",
  "enabled": true,
  "name": "headerauth"
}
```

Here, the plugin has been successfully created and enabled. 

If you make the same request against the mockbin API again:

```bash
$ curl -i -X GET \
  --url http://localhost:8000/ \
  --header 'Host: mockbin.com'
HTTP/1.1 403 Forbidden
...
{ "message": "Your authentication credentials are invalid" }
```

This request did not provide a header named `apikey` (as specified by our plugin configuration) and is thus Forbidden. Kong does not proxy the request to the final API.

To authenticate against your API, you now need to create an account associated with an application. An application links an account and a plugin, this way, an account can consume different APIs with different applications (and different keys).

```bash
$ curl -i -X POST \ 
  --url http://localhost:8001/accounts/
  --data ''
HTTP/1.1 201 Created

# Make sure the given account_id matches the freshly created account
$ curl -i -X POST \
  --url http://localhost:8001/applications/
  --data 'public_key=123456&account_id=<account_id>'
HTTP/1.1 201 Created
```

That application (which has `123456` as an API key) can now consume APIs having an authentication requirement such as our example. If we make the same query again, but with an `apikey` header:

```bash
$ curl -i -X GET \
  --url http://localhost:8000/ \
  --header 'Host: mockbin.com' \
  --header 'apikey: 123456'
HTTP/1.1 200 OK
```

Your user can now consume this API.

To go further into mastering Kong and its plugins, refer to the complete [documentation](#documentation).

**Comment by thibaultCha** [comment]
The README could probably still contain the 1st part (adding an API and querying it) with a link to the website and the full Getting Started.

Again, feel free to improve.

**Comment by montanaflynn** [comment]
The section "Accounts and plugins" is the most complicated and confusing because it doesn't mention applications in the header and starts off with enabling a plugin. How APIs, accounts, applications and plugins interact with each other could be better explained in this section.

Actually I think it should be broken into three sections:

- Adding an account
- Adding an application
- Enabling headerauth plugin

**Comment by montanaflynn** [comment]
I find it weird that we have applications / accounts in the core if they are required for the auth plugins, maybe I'm not seeing the bigger picture use for them? Like will all plugins will have access to them and you can enable plugins on a per account or application basis?

**Comment by thibaultCha** [comment]
> Adding an account
> Adding an application
> Enabling headerauth plugin

Yep, I was wondering wether or not I should use that order instead.

> I find it weird that we have applications / accounts in the core if they are required for the auth plugins,

Valid point, to discuss in meeting

**Pull request merged**
