### PR TITLE
fix(bot-detection) honor cache ttl and simplify

### PR DESCRIPTION
**Pull request by Tieske**
Manual invalidations wil not honor periodic expiration. Besides that this will simplify the implementation a lot.

replaces #2673

Note: creating the lru-cache would ideally be done in the second level callback of the new `mlcache` library, in the step of deserialising shm based scalar data to the lua-land representation.

### CODE REVIEW

**Comment by p0pr0ck5** [comment]
Where is this code change are TTLs actually handled? And I'm not even sure how TTLs are relevant here?

**Comment by p0pr0ck5** [comment]
Also is `conf` a mutable object? when are we saving the value of `conf` back to mlcache?

**Comment by thibaultcha** [comment]
Hmmm not bad, this takes advantage of the caching of the `conf` table here https://github.com/Mashape/kong/blob/next/kong/core/plugins_iterator.lua#L48

Although a bit hacky, because `conf` should be read-only, and identical in each worker's Lua land...

**Comment by Tieske** [comment]
> Where is this code change are TTLs actually handled? And I'm not even sure how TTLs are relevant here?

The new `ttl` setting from the `serf` replacement that invalidates the cache each hour. `conf` is just an entity we get from the DB, like any other, and hence is subject to that ttl.

> Also is `conf` a mutable object? when are we saving the value of conf back to mlcache? 

It was not mutable in the past (only shm based caching) as it would have a request-based-lifetime in lua-land. But since we added lua-land caching it lives until invalidated.

> Although a bit hacky, because `conf` should be read-only, and identical in each worker's Lua land...

It's hacky only if you look at it from the shm based cache. You could also consider the `conf` table to be an instance of a plugin, so it's a matter of definition. (technically you could even set the plugin table as the meta-table and actually make it a plugin instance)

It's made easy because we never need to serialize data, it only travels from the DB up, through shm to Lua-land, and in each step we enrich it. Hence I've been advocating the second-level callback for mlcache, exactly for this usage.

The main distinction we should make imo is the initialise vs runtime code separation. 'Initialise' being the deserialisation from shm-scalars to lua-land, and 'runtime' being the handler execution. In this case the lru creation should be part of deserialisation/initialisation and then we could skip the check at runtime.

See [this code](https://github.com/Mashape/kong/blob/master/kong/plugins/http-log/handler.lua#L75) for a similar example. Here we parse the url on _every_ request, over and over again, a complete waste of cpu cycles.

**Comment by p0pr0ck5** [comment]
Okay, at first I though we were talking about the TTL of each cache entry in the `ua_cache` LRU. That clears up my confusion there :)

I think making `conf` mutable in cases like this has its value, if we actually design it to behave in such a way (e.g., a refactor of the plugins loop). In lieu of this, I can't say I'm a fan of this approach here; it only obfuscates what's going on here, with no gain (apart from TTLs, which can just be leveraged using the native TTL lrucache mechanism). We're making this path much less explicit, and leveraging an undocumented "feature" of the existing environment. IMO this is dangerous. At the absolute very least, the code surrounding this needs to have a well-written paragraph comment explaining whats going on here; undocumented hand-wavy black magic isn't going to help any future archaeology efforts :)

**Comment by Tieske** [comment]
@p0pr0ck5 I also don't think we should be merging this now. It's just an example for future reference, and only makes sense if we consistently apply this to all plugins. Only in one plugin is indeed too much magic. Also just discussed this with @thibaultcha .

Regarding the `conf` table being immutable; that's not really a concern, the data in that table is "owned" by the plugin, as it is defined by its schema. The table is stored in the cache, and the plugin is free to do with its contents as it likes. No other code will ever touch it.

For now I'll close it, but let's keep it in mind when the refactor of the plugin api/runloop comes up.

**Comment by Tieske** [comment]
just for reference, within the current design and patterns we could have done this:

```lua
-- use a cache table with weak keys
-- the key is the `conf` table, the cache-lru mechanism is already covered
-- by the default caching of `conf`.
-- No invalidations or whatsoever are necessary

local cache = setmetatable( {}, { __mode = "k" })

_M.handler = function(conf)
  local my_conf = cache[conf] -- conf table as weak-key for the cache
  if not my_conf then
    my_conf = {}
    -- here go off and regenerate the config...
    
    
    cache[conf] = my_conf
  end
  
  -- from here on use `my_conf`
end
```

When the plugin configuration changes, there will be a new `conf` table, hence the `my_conf` will be regenerated. The old `conf` table will go out of scope (when it is invalidated in the regular cache). Once that happens, the Lua GC will remove it from the `cache` table as it is a weak key.

So stupid I didn't think of this before...

**Comment by thibaultcha** [comment]
This approach is nice, but would still require an LRU cache inside of `my_conf` to avoid the possibility of flooding with different values before its TTL is reached.

**Pull request closed without merging**
