### PR TITLE
Fix retrieving oauth2 params from body

### PR DESCRIPTION
**Pull request by eddmann**
### Summary

There is an issue when you supply a JSON request with an empty body to the OAuth2 plugin.
As the body is deemed to be 'nil' the JSON decode function does not like this (as it expects a string) and throws.

### Issues resolved

This commit short circuits the retrieval process if the request method is GET or HEAD (as these do not provide bodies), and in the event that no body is supplied in another request type it provides a default empty JSON object to satisfy the decode process.

### CODE REVIEW

**Comment by eddmann** [comment]
Having issues setting up the `kong-vagrant` box as it complains about `resty` not being available so have not been able to include and run test-suite against the changes.

**Comment by Tieske** [comment]
see also #1773

**Comment by djMax** [comment]
This bug hits us too...

**Comment by thefosk** [comment]
Closed with #1915

**Pull request closed without merging**
