### PR TITLE
 requestsizelimiting: use a resolved headers and minor typo fix

### PR DESCRIPTION
**Pull request by ajayk**

### CODE REVIEW

**Comment by ahmadnassri** [comment]
:+1: good catch on that typo :)

**Comment by thibaultCha** [comment]
Sounds good but needs rebasing.

**Comment by ajayk** [comment]
@thibaultCha closing this and opening a new pull request due to a merge conflict

**Comment by thibaultCha** [comment]
That was not necessary. The point of rebasing is to fix the conflicts before merging this

**Comment by ajayk** [comment]
@thibaultCha i had trouble merging next time i will probably take your help

**Pull request closed without merging**
