### PR TITLE
Add Changelog episode badge to README

### PR DESCRIPTION
**Pull request by jerodsanto**
Thanks for coming on the show @ahmadnassri! We've added this badge to the README to share your episode with your community. :beers: 

Links to: https://changelog.com/185

### CODE REVIEW

**Comment by adamstac** [comment]
Ditto! Great show. 💯🍻

**Comment by ahmadnassri** [comment]
thanks guys!

**Comment by thibaultCha** [comment]
Awesome, just finished listening to it, thanks for having Kong on the show!

**Comment by sinzone** [comment]
sleek!

**Pull request merged**
