### PR TITLE
Provide better Puppet module link

### PR DESCRIPTION
**Pull request by juniorsysadmin**
I am slightly biased but believe my module is better than the one listed in the README and more likely to be maintained.

### CODE REVIEW

**Comment by sinzone** [comment]
perhaps better to keep both.

**Comment by thefosk** [comment]
@juniorsysadmin can you update the PR to keep them both for the time being?

**Comment by juniorsysadmin** [comment]
> @juniorsysadmin can you update the PR to keep them both for the time being?

Done

**Comment by thefosk** [comment]
@juniorsysadmin thank you - if you could also squash the commits I will then proceed and merge the PR in both `master` and `next`.

**Comment by juniorsysadmin** [comment]
Hold off merging just yet

**Comment by juniorsysadmin** [comment]
> @juniorsysadmin thank you - if you could also squash the commits I will then proceed and merge the PR in both master and next.

Okay done, ready for merging.

**Comment by thibaultCha** [comment]
Manually merged to master and next, thank you!

**Pull request closed without merging**
