### PR TITLE
feature (ldap) LDAP plugin for user authentication

### PR DESCRIPTION
**Pull request by shashiranjan84**
Plugin authenticates user against LDAP Server

### CODE REVIEW

**Comment by thibaultCha** [comment]
Could you fix the conflicts before merging?

**Comment by shashiranjan84** [comment]
@thefosk  Should we hold on this as we planning to develop pure Lua implementation for LDAP Client supporting cosocket.

**Comment by thibaultCha** [comment]
I am all in favor for waiting. I thought you guys wanted to still push this out with the LDAP binding.

**Comment by shashiranjan84** [comment]
closing thins PR, will be sending another PR soon

**Pull request closed without merging**
