### PR TITLE
Vagrant implementation and documentation

### PR DESCRIPTION
**Pull request by jasonmotylinski-dowjones**
I wanted to create an isolated development environment. I added a Vagrantfile and setup script which installs all the necessary dependencies for Kong development.

The README.md contains instructions for starting the Vagrant box, compiling Kong, and verifying everything works.

### CODE REVIEW

**Comment by sinzone** [comment]
thank you @jasonmotylinski-dowjones. We'll look into this one.

**Comment by ahmadnassri** [comment]
nicely done!

**Comment by thibaultCha** [comment]
Thank you for this,

I just tried it out, worked like a charm. I would have a few comments about it tho:

- if you want less dependency and faster setup time:
  - `lua5.1` and `liblua5.1-0-dev` aren't really required, you can simply install Openresty first (if you have the dependencies) and it comes with LuaJIT. Then install Luarocks with LuaJIT support.
  - I think you are installing openssl twice (once in `Vagrantfile` and once in `setup.sh`
  - `libcurl4-openssl-dev` not sure if this one is really required either
  - Another way to quickly and simply install Kong is to install the latest [package](http://getkong.org/download/) and simply run Kong's `make install` (since mostly only Kong's Lua code changes between version)
- `setup.sh` should probably give permission to the `vagrant` user on `/usr/local` or at least `/usr/local/kong`. So that `kong start` can work without sudo.
- The instructions should probably mention a little bit more about the development environment. For example, the fact that `make start` is an alias to `kong start -c kong_DEVELOPMENT.yml` and will use the local files (the mounted `/kong` folder) and not the ones installed by `make install` (in `/usr/local/kong`). It could also explain that the `lua_code_cache` directive is `off` in the development config and that the combination of those two settings allows a developer to edit the local files (on the host machine) and instantly test his code without having to restart Kong. A link to the README's Makefile operations can be very useful too.

##### Decoupling repos

As a side note, I would add something more general: this repo (Mashape/kong) is ultimately aimed at being what we internally call "kong-core", which should be as lean as possible. It should only contain the actual code needed to proxy requests, install and run plugins + tests related to it. As of today it also contains every plugins and their respective tests, which is not what we want on the long term since it makes the repo over sized, harder to maintain and too limited for plugin authors.

Ideally, everything related to `distributions` (distribution scripts and packages) should be outsourced from the repo too. The same way we have `docker-kong`, we should have `distributions-kong` (with the scripts to build the packages) and, I think you're seeing me coming here: I am wondering if `vagrant-kong` would make sense too.

The end goal is to arrive to something similar to this in terms of structure:
- kong-core (this repo): things currently in `kong/` and their tests.
- kong-plugin-xxx: any plugin, outsourced in a different git repository and its related tests
- kong-docker: the docker distribution
- kong-vagrant: the Vagrant distribution (aimed at developers)
- kong-distributions: scripts related to platform packages (the current `distributions` folder)

I think we have a lot to gain from a leaner kong-core. That is still an open discussion so feel free to add thoughts on that.

---

In the meantime, I am fine with merging this PR and slightly improve the docs and/or the Vagrant file later. Since the decoupling in multiple repo will be done later anyways if it happens.

**Comment by thibaultCha** [comment]
For emails: original comment edited.

**Comment by jasonmotylinski-dowjones** [comment]
I like the idea of decoupling the repositories. It creates a cleaner separation of features as well as a single responsibility for each repository. 

Let me take a stab at creating a repository specifically for a Kong Vagrant setup with your suggestions implemented.

**Comment by thibaultCha** [comment]
@jasonmotylinski-dowjones I just created a repository at Mashape/kong-vagrant and invited as a contributor, feel free to push there! Thank you

(I will later update the README to point developers/users to those repos)

**Comment by thibaultCha** [comment]
Thanks again for this, I have moved the Vagrantfile here: https://github.com/Mashape/kong-vagrant

This new repo and the docker one (including future others) will be listed in this repo's readme.

**Pull request closed without merging**
