### PR TITLE
fix(key-auth) don't crash when conf.anonymous is nil

### PR DESCRIPTION
**Pull request by Vermeille**

### CODE REVIEW

**Comment by Tieske** [comment]
@Vermeille how did you set the property to `nil` ? From what I see, it can only be an empty string?

**Comment by Vermeille** [comment]
Not sure. It was nil after I migrated from 0.9.9, and explicitly setting it to "" is not solving anything.

**Comment by Tieske** [comment]
The default value is "", hence the extra test at runtime can be omitted (performance)

**Comment by Vermeille** [comment]
So I thought. But I somehow managed to have this nil value instead of "". Any idea why?

```
$ curl 127.0.0.1:8002/apis/https-bench-service/plugins/b7ad7b2a-ef5b-4c77-cc91-0a29deb1d7ee | jq
{
  "api_id": "b7ad7b2a-ef5b-4c77-cc91-0a29deb1d7ee",
  "id": "b7ad7b2a-ef5b-4c77-cc91-0a29deb1d7ee",
  "created_at": 1476703979000,
  "enabled": true,
  "name": "key-auth",
  "config": {
    "anonymous": "",
    "key_names": [
      "X-Client-ID"
    ],
    "hide_credentials": false
  }
}
```

**Comment by Tieske** [comment]
That's because no migration was added to explicitly set missing field to the default "" value.

**Comment by Vermeille** [comment]
I am not sure I'm being clear.
Despite explicitly setting config.anonymous="" via the admin endpoint as you can see above, I still have `conf.anonymous == nil`

**Comment by Tieske** [comment]
see #2266.

closing this.

**Comment by Tieske** [comment]
@Vermeille thx for the report!

**Pull request closed without merging**
