### PR TITLE
fix(router) various fixes and improvements

### LINKED ISSUE #2073: The path portion of the upstream_url is missing
### Summary

When we create an API, and set its upstream_url with a path, then we request this API, we can't  access the upstream_url with path, but only access the root url.

### Steps To Reproduce

1.create an API by client like this:

    {
      name = 'python-kong',
      uris = '/python-kong',
      upstream_url = 'https://github.com/vikingco/python-kong',
    }

2.visit the following URL from my browser:
`https://{nginx-host}/python-kong/`

3.the result is not the page of URL `https://github.com/vikingco/python-kong/`, but the home page`https://github.com/`!

### Additional Details & Logs

- Kong version (0.10.0rc3)
- Operating System (centos6.3)

### PR DESCRIPTION
**Pull request by thibaultcha**
This initially started as a proper fix for #2073 (raised by @javeme), since the initial fix proposed was incomplete (missing tests and undesired Nginx variable) and the fix was quite urgent (currently affecting all 0.10.0 RCs), this supersedes the proposed fix. Additionally, I discovered another issue with the router's priorities that were off-base in some edge-case.

### Full changelog

* avoid HTTP method to supersede non-plain URI
* preserve upstream_url path component if exists
* prefer ngx_re API to ensure JIT

Bonus:
* simpler return values for exec() API

### Issues resolved

Fix #2073 
Supersede #2074

**Note**: do **NOT** squash for better future tracking in case those commits introduce an issue.

### CODE REVIEW

**Comment by Tieske** [comment]
this might also explain some of the test failures with oauth2 and rate limiting

**Comment by DonMartin76** [comment]
Does this fix the issue with `<api>/oauth2/token` not being reachable when using `uris` instead of `hosts`?

**Comment by thibaultcha** [comment]
@DonMartin76 Would appreciate if you try it out and see if it does.

**Comment by DonMartin76** [comment]
@thibaultcha It does not fix it. Steps to reproduce:

```bash
curl -d 'name=hello&uris=/mockbin&upstream_url=http://mockbin.org' http://localhost:8001/apis
curl -d 'name=oauth2&config.enable_client_credentials=true' http://localhost:8001/apis/hello/plugins
curl -d 'username=someuser' http://localhost:8001/consumers
curl -d 'name=oauth2&client_id=some_id&client_secret=some_secret&redirect_uri=http://dummy.org' http://localhost:8001/consumers/someuser/oauth2
curl -d 'grant_type=client_credentials&client_id=some_id&client_secret=some_secret' --insecure https://localhost:8443/mockbin/oauth2/token
```

The last `curl` must return an access token. The equivalent when using hosts works:

```
curl -d 'name=olleh&hosts=binmock.org&upstream_url=http://mockbin.org' http://localhost:8001/apis
curl -d 'name=oauth2&config.enable_client_credentials=true' http://localhost:8001/apis/olleh/plugins
curl -d 'username=otheruser' http://localhost:8001/consumers
curl -d 'name=oauth2&client_id=other_id&client_secret=other_secret&redirect_uri=http://dummy.org' http://localhost:8001/consumers/otheruser/oauth2
curl -H 'Host: binmock.org' -d 'grant_type=client_credentials&client_id=other_id&client_secret=other_secret' --insecure https://localhost:8443/oauth2/token
```

**Comment by thibaultcha** [comment]
Well, this is out of the scope of this PR then. Thanks for checking still.

**Comment by DonMartin76** [comment]
Np. Is there a bug for the above behaviour already? Or should I file a new issue?

**Comment by thibaultcha** [comment]
This could actually be due to how the router now works. I am not the least familiar with the OAuth2 plugin but I'll take a look.

**Comment by DonMartin76** [comment]
👍

**Comment by thibaultcha** [comment]
@DonMartin76 Mind trying out #2086?

**Pull request merged**
