### PR TITLE
Renaming analytics to mashape-analytics

### PR DESCRIPTION
**Pull request by thibaultCha**
- Dash is nicer for readability than underscore, especially when writing HTTP requests: it feels more user friendly.
- 'analytics' thus becomes 'mashape-analytics'

### CODE REVIEW

**Comment by thefosk** [comment]
This will affect installed plugins already in the database, and it needs a data migration script.

**Comment by thibaultCha** [comment]
Oh yes I forgot but the request size is already in 0.3? The underscore does seem wrong tho.

**Comment by thefosk** [comment]
Also the request and response transformations.

**Comment by thibaultCha** [comment]
Let’s just rename mashape-analytics for now but keep in mind that we need to rename other plugins too.

**Pull request merged**
