### PR TITLE
feat(schema): regex for numbers

### PR DESCRIPTION
**Pull request by pauldaustin**
### Summary

Implement schema regex validation for number types.

### Full changelog

* Implement schema regex validation for number types.
* Add numeric regex validation test

### CODE REVIEW

**Comment by thibaultcha** [comment]
This is definitely a legacy part of the code that I am *very* reluctant to adding more features to it. I'd suggest to write your own validation function for your schema if you wish to perform such a check. It will most certainly serve you in the future according to our plans for refactoring how entities are validated.

**Comment by thibaultcha** [comment]
The use-case also seems to be very narrow, maybe not worth adding yet another abstraction in there if it will rarely be used in schemas.

**Comment by Tieske** [comment]
I agree with @thibaultcha , closing this.

**Comment by pauldaustin** [comment]
I've deleted the branch and will add validation to my plug-in.

Could you update the documentation https://getkong.org/docs/0.9.x/plugin-development/plugin-configuration/ to note that the regex only applies to string fields?

**Comment by Tieske** [comment]
@pauldaustin just did :+1: (not published yet)

**Pull request closed without merging**
