### PR TITLE
Add gitter badge

### PR DESCRIPTION
**Pull request by lookfirst**

### CODE REVIEW

**Comment by thibaultCha** [comment]
I am actually not sure that we want it as a badge, it was removed by @montanaflynn a few hours ago, I do not know why. I would suggest (if we are going to bring it back) to style it as the other badges (see how [Mockbin](https://github.com/Mashape/mockbin) does it (with a flat style but it doesn't matter).

```
[gitter-url]: https://gitter.im/Mashape/kong
[gitter-image]: https://img.shields.io/badge/Gitter-Join%20Chat-blue.svg
```

**Comment by lookfirst** [comment]
Oh funny... sorry, I didn't see it as removed previously.

**Comment by lookfirst** [comment]
Also, I've been trying to sign the CLA, but can't. It just gives me a useless error, screenshot: http://take.ms/XajDy

**Comment by montanaflynn** [comment]
Thanks for the first PR! When I added google groups I moved the Gitter chat link under it. No problem with adding the badge back if it's easily missed. I like @thibaultCha's suggestion about the badge style.

We'll find out what's going on with that issue and let you know when it's fixed. Sorry about that.

**Comment by Nijikokun** [comment]
@lookfirst the CLA form has been moved to a [google form](https://docs.google.com/a/mashape.com/forms/d/1TD65FNdgcPHi0bgkEkNwdw3FLbx_feZWaqyF6sgytGc/viewform) once you sign this we can merge :+1:

**Pull request merged**
