### PR TITLE
Check for valid signature in hmac-auth plugin before comparing digests.

### PR DESCRIPTION
**Pull request by vaibhavatul47**
### Summary

* Inside Hmac-Auth `access.lua` if invalid base64 encoded signature is passed to Kong then Kong returns, "Kong Error" because there is no check whether a proper signature is passed or not. I have added a `nil` check before comparing the lengths of the two digests so that Kong can return "Unauthorised" message in case of an invalid signature.
* Also previously, length of the same digest was compared which would always return true, so I have fixed it

### Full changelog

To reproduce:
1. Create an API and a consumer.
2. Add Hmac-auth to the API and create a credential for the consumer.
3. Call the API with and invalid base64 encoded signature.
[ This will result in Kong Error. HttpStatus code: 500 ]

I have fixed this issue in following steps:
1. Check if base64 decoded signature is not `nil`
2. Compare lengths of `computed digest` (digest_1) and `received digest` (digest_2). Earlier, the length of the same digest was compared which will always return `true`.

Ps: Not every invalid signature returns HTTP 500. Only those signatures which won't be decoded successfully by base64 will result in HTTP500, rest will return HTTP 403 `Unauthorised`.

### CODE REVIEW

**Comment by vaibhavatul47** [comment]
The 2 out of 6 checks which have failed in Travis are related to  `ACL` and `Ring-balancer`, thus not due to this commit. I don't know why they failed.

**Comment by Tieske** [comment]
@vaibhavatul47 I had a look at this, but I'm unable to reproduce your issue. How did you make it fail?

**Comment by vaibhavatul47** [comment]
@Tieske It will fail when the signature is not properly base64 encoded. I've added a test case.

**Comment by Tieske** [comment]
@vaibhavatul47 That test case already passes for me (without your fix)

**Comment by Tieske** [comment]
fixed by #2283 , closing this.

@vaibhavatul47 Many thanks for the report!

**Pull request closed without merging**
