### PR TITLE
Document/readme

### PR DESCRIPTION
**Pull request by montanaflynn**
@thibaultCha can you suggest how to squash the commits?

### CODE REVIEW

**Comment by thibaultCha** [comment]
Here you have a problem because you have my commit in the middle.

I would suggest the simplest way:

```
git checkout master
git checkout -b tmp_branch
git cherry-pick 7840ec3
git cherry-pick 0abb1b4
(resolve any conflict during those cherry picks) to resolve edit, add, and git cherry-pick --continue
git rebase -i HEAD~2
replace pick on the latest commit by "squash" or s
save/exit
git push -f
```

**Comment by thibaultCha** [comment]
Added a part with **edit with a new commit message**

**Comment by thibaultCha** [comment]
Also add the following to your gitconfig:

```
[pull]
  rebase = true
```

To avoid merges when pulling

**Comment by montanaflynn** [comment]
Thanks!

**Comment by thibaultCha** [comment]
:+1: Don't forget to delete your branch tho, thanks

**Pull request merged**
