### PR TITLE
feat(admin) endpoint to explicitly clean upstream targets

### PR DESCRIPTION
**Pull request by p0pr0ck5**
Modify the abstracted cleaning function to take a load factor,
rather than the hardcoded value of 10 previous defined. This allows
users to clean targets at an arbitrary rate, and allows for cleaning
without needed to add a new target.

### CODE REVIEW

**Comment by Tieske** [comment]
If I read it correctly, we can now speedup cleaning, but not slow it down. Correct?

Ideally I'd like to see a cleanup factor configured per upstream, where 0 = never. And calling the cleanup endpoint just cleans. This allows to time cleanup to 'slow times' on manual

**Comment by p0pr0ck5** [comment]
I wouldn't be opposed to that, but I think it's outside the scope of this PR, and could be implemented as a separate patch. Thoughts?

Anything about this PR specifically that needs adjusting?

**Comment by Tieske** [comment]
But then create that, and close this. Merging doesn't make sense imo.

**Comment by p0pr0ck5** [comment]
> Merging doesn't make sense imo.

Why not? What specifically is wrong with this PR? Why can't we have both feature sets?

This feels like being objectionist for objectionism's sake. Unless there's a valid reason not to have this functionality in the codebase, I don't how wanting to have a per-upstream cleanup factor has to do with this not being appropriate to merge?

**Comment by p0pr0ck5** [comment]
Let's say I have a long, dirty history of targets that haven't been cleaned. As the codebase currently stands, in order to clean this history, I have to POST a _new_ target. This doesn't make sense to me imo. This PR allows a user to clean the history without the need to POST a new target. The configurable cleanup factor is a nice extra bit, but the underlying problem that this PR solves is the inability to clean history without creating a new target entry.

**Comment by Tieske** [comment]
>This feels like being objectionist for objectionism's sake.

no intent.

the odd case for that scenario is the cleanup factor being a parameter in this. If you pull that out, it just becomes and endpoint to do a cleanup now.

Then later we can add the configurable cleanup factor per upstream. without then having some legacy with an odd cleanup factor in there.  Just my 2cts.

You could look at this as if the cleanup factor is/becomes technical debt. And then imo don't add it in the first place (the cleanup factor in the endpoint).

**Comment by p0pr0ck5** [comment]
If the work to add in the configurable cleanup factor here was a large, bulky commit that made a major change on the API or the processing of targets, I would call that technical debt. But this is a very small change, of an optional function param, with no change to behaviors of existing endpoints. This hardly feels like technical debt to me :) And if we want per-upstream cleanup factors, this `clean_history` function needs to be modified to take the cleanup factor as a param anyway, no? So this is not tech debt. This is a simple, easy convenience function for a less-than-intuitive interface. :)

**Comment by Tieske** [comment]
the cleanup factor should become part of the upstream entity, not a parameter in some rest call.

If we add it now, we cannot pull it out later without breaking backward compatibility. Hence: imo don't add it.

Also, the cleanest interface would be the one where calling for a cleanup, would actually do an immediate cleanup, instead of having to add some parameter which might or might-not result in a cleanup.

**Comment by Tieske** [comment]
@poprocks oops... there is a big issue with this PR!

Sorry for not noticing it before.

To explain: see [this code](https://github.com/Mashape/kong/blob/e5c21c9173ae97a9df3a9a0dc78190d03011e77f/kong/api/routes/upstreams.lua#L114-L116) and [this comment](https://github.com/Mashape/kong/blob/e5c21c9173ae97a9df3a9a0dc78190d03011e77f/kong/api/routes/upstreams.lua#L52-L53)

That code cleans the history, and then posts the new target. It relied on the posting of the new target to generate the invalidation event.

So in short: this implementation will not propagate the event, and the active running balancers will not be updated. It needs an integration test that proves that the balancer was updated after the cleanup.

The same applies for the delete method that was implemented. I'm not sure whether [that dao call](https://github.com/Mashape/kong/blob/e5c21c9173ae97a9df3a9a0dc78190d03011e77f/kong/api/routes/upstreams.lua#L186) actually send an event (think it does), but requires a similar integration test to prove it anyway.

**Comment by p0pr0ck5** [comment]
> That code cleans the history, and then posts the new target. It relied on the posting of the new target to generate the invalidation event.
>
> So in short: this implementation will not propagate the event, and the active running balancers will not be updated. It needs an integration test that proves that the balancer was updated after the cleanup.

Eagle eyes @Tieske! I didn't catch that. Sounds like it's best to just scrap this for now.

> The same applies for the delete method that was implemented. I'm not sure whether that dao call actually send an event (think it does), but requires a similar integration test to prove it anyway.

Did you just ask for an integration test to provide the functionality of `kong.api.crud_helpers.post`? :D

**Pull request closed without merging**
