### PR TITLE
Add Client IP claim (cip) to JWT plugin

### PR DESCRIPTION
**Pull request by thehighlander**
- add cip claim to counter replay attacks.
- add cip tests to jwt_parser_spec
- add cip tests to access_spec

### CODE REVIEW

**Comment by p0pr0ck5** [comment]
@thehighlander,

Thanks for the PR! Can you clarify, what part of RFC7519 is the 'cip' claim?

**Comment by thehighlander** [comment]
@p0pr0ck5 It's not part of the RFC - it's just meant to be an additional optional validation. We were going to add it no matter what, so I figured I'd just give it back.

**Comment by p0pr0ck5** [comment]
@bungle do you have thoughts here, given your recent work?

**Comment by bungle** [comment]
I'm not against it, but:

- it is totally proprietary
- nat, proxies (either forward or reverse), x-forwarded headers may make it harder to use this (especially in dynamic configurations where the remote address can even change or in mobile scenarios where your IP may change when you change the access point etc.).

We could include it with some remarks. There are many standard claims that could be added as well. I can see the value, but I have a bit mixed feelings about it.

A standard close to this in JWT scene is probably this:
https://tools.ietf.org/html/rfc7800

**Comment by thehighlander** [comment]
@bungle I considered a more flexible approach to allow me to plug-in individual claims & claim handlers, then make claims_to_validate completely dynamic instead of constants in the code. Given the simplicity of the plugin as-is, it seemed like adding too much icing when there just isn't much cake. Also, I'm new to lua so I didn't really have the expertise to create a plugin... for a plugin.

**Comment by thibaultcha** [comment]
Considering this isn't part of the standard, I would be opposed to such a change, and take a different approach. Like you suggested @thehighlander, it has been a long time goal for this plugin to be able to validate arbitrary claims with user-provided code, simply because there is no way for us to support all possible additions to the spec without it becoming some king of big mess.

Instead of setting a precedent and accepting this, I would rather wait until we support arbitrary claims verification (I know @bungle has been doing some work around this recently, for our Enterprise Edition.)

Precipitate things and accepting this would either result in adding more of such non standardized claims because we set a precedent, or breaking the integration of all users relying on it once we release a proper arbitrary claims verification.

**Comment by thehighlander** [comment]
@thibaultcha  I've already duped the existing jwt plugin and used it as a custom plugin instead of trying to do the non-standard claim. closing PR.

**Pull request closed without merging**
