### PR TITLE
Feature/piwik log

### PR DESCRIPTION
**Pull request by derDieDasJojo**
**Note: new features are to be opened against next, hotfixes against master.**
### Summary

Implemented a plugin to send request logs to piwik

### CODE REVIEW

**Comment by thibaultcha** [comment]
Hi,

This duplicates a lot of code from existing  plugins. Additionally, if we keep going down that path we'll end up with a plugin for each and every analytics service out there, instead of the 3 originally planned: `tcp-log`/`udp-log`/`http-log` plus the `galileo` one which is special because of its serializer and buffering.

What is missing from the http-log plugin to send data to piwik? Would it need a different serializer? I think that instead of creating a plugin for every service out there, logging plugins (distinct from each other by their protocol) should receive a `platform` configuration, which depending on its value will log slightly different payloads to different services - for example.

**Comment by derDieDasJojo** [comment]
Piwik doesn't want simply the request to be forwarded but instead expects an Request with very [clearly specified parameters](http://developer.piwik.org/api-reference/tracking-api). I did not see a way to do this simply with http-log.
If there is a way to this with http-log. lets go for this.
Do you have a example for this platform configuration approach ?
If it is not possible i think creating a new plugin is an apropriate choice.

**Comment by thibaultcha** [comment]
Yes, like I said, we would be better off implementing different serializers for each supported service than to implement a new plugin every time. This was the original intent, and is the reason why there exist different serializers:

https://github.com/Mashape/kong/tree/master/kong/plugins/log-serializers

The approach I'd rather see, however, would probably to make the `http-log` plugin (and counterparts) accept pluggable serializers depending on the receiving service (piwik, runscope, ...).

**Comment by derDieDasJojo** [comment]
ok. I could try the following approach:
1) write a serializer for piwik
2) refactor piwik-log to use the new piwik-serializer and as many function as possible directly from http-log.
is that be an acceptable approach ?

**Comment by thibaultcha** [comment]
I think the best approach would - globally - be:

1) make the `http-log` plugin accept a `serializer` property, with values such as `basic`,`piwik`, etc...
2) implement a `piwik` serializer 
3) discuss what we should do with the existing plugins already duplicating `http-log` (deprecating them and convert them into serializers.

The property could either be the serializer to use itself, or named something like `service`. It could make a difference if some logging services expect other tweaks than just changing the serializer (different URIs, different HTTP requests and authentications, etc...) This ought to be evaluated and discussed first.

**Comment by derDieDasJojo** [comment]
and then we would add a field to [http-log' s schema.lua](https://github.com/Mashape/kong/blob/master/kong/plugins/http-log/schema.lua) to choose which serializer to use ?

**Comment by thibaultcha** [comment]
> and then we would add a field to http-log' s schema.lua to choose which serializer to use ?

That is the property I talked about, yes.

**Comment by derDieDasJojo** [comment]
alright. I could start implementing this on thursday - have to leave now. Thanks for your support.

**Comment by Tieske** [comment]
sorry, bit late to the party. The existing approach is to use inheritance.

See https://github.com/Mashape/kong/pull/1690 for an example of reusing the existing http-log code. As the serializer is specific to this plugin, its code can be located in the plugin as with this example.

**Comment by thibaultcha** [comment]
I don't think this is related to the discussion we're having about implementing several serializer, which is a better long term solution.

**Comment by derDieDasJojo** [comment]
I realized that I don't have the time to implement the modifications you wished.
But I would be happy if it would find a way to the main repo.
Maybe I sooner or later I will have the time to care of it myself - We will see.
I created a working fork with dockerfiles on: https://github.com/derdiedasjojo/docker-kong
You can use it how every you want. (BSD-License and public domain).

**Comment by thibaultcha** [comment]
Closing this because of a lack of updates and since we became quite reticent as to merging third-party plugins into the main repository for obvious maintainability reasons. Thank you for your contribution, I strongly suggest that you maintain this plugin on your own on GitHub and publish it on Luarocks for everybody else out there, until we provide our own Kong plugins manager.

**Pull request closed without merging**
