### PR TITLE
Changed URL of cloned repo

### PR DESCRIPTION
**Pull request by gjedeer**
the git clone URL from the docs returned:

Permission denied (publickey).

since I don't have commit access. I changed that to https://... URL

### CODE REVIEW

**Comment by harlow** [comment]
Is it possible your SSH keys are not set up with GitHub correctly? I'm not a contributor to Kong and can use `git clone https://github.com/Mashape/kong.git` w/ no problem.

```
~/Desktop $ git clone git@github.com:Mashape/kong.git
Cloning into 'kong'...
remote: Counting objects: 13543, done.
remote: Total 13543 (delta 0), reused 0 (delta 0), pack-reused 13543
Receiving objects: 100% (13543/13543), 2.09 MiB | 808.00 KiB/s, done.
Resolving deltas: 100% (7974/7974), done.
Checking connectivity... done.
```

**Comment by gjedeer** [comment]
Well, I don't keep my personal keys on the server where I run kong, and i don't want to associate server keys with my account.

**Comment by harlow** [comment]
@gjedeer that makes a lot of sense! :+1: The commit message made it sound like it had something to do w/ commit access.

**Comment by gjedeer** [comment]
Right. Sorry about that message, now that I read it it's terrible :)

**Comment by thibaultCha** [comment]
Why not, thanks

**Pull request merged**
