### PR TITLE
Added debug tools/scripts and documentation

### PR DESCRIPTION
**Pull request by Tieske**

### CODE REVIEW

**Comment by thibaultCha** [comment]
Not a fan. This is too opinionated/platform/IDE specific to be included in the core imho.

**Comment by thibaultCha** [comment]
Having a gist or a blog post or a page on the website describing this and a link to it in the Kong README is more appropriated.

**Comment by Tieske** [comment]
How about putting it in a separate github repo and have link to the readme from the plugin development pages on the site somewhere?

**Comment by thibaultCha** [comment]
That works for me too. It should maybe also document other ways of debugging, such as [ngx-gdb-utils](https://github.com/openresty/nginx-gdb-utils) or [https://openresty.org/#Debugging](https://openresty.org/#Debugging) (which mentions checking the error log) combined with [inspect.lua](https://github.com/kikito/inspect.lua) for light debugging for example.

**Comment by thibaultCha** [comment]
`kong-devel-utils` maybe

**Pull request closed without merging**
