### PR TITLE
Refactor/normalization schema

### PR DESCRIPTION
**Pull request by thefosk**
@thibaultCha I would like to merge this into `0.1.0`

### CODE REVIEW

**Comment by thibaultCha** [comment]
Tests don't pass. https://github.com/Mashape/kong/pull/100 They do on the first commit, I'm sure it didn't need much work to polish it.

**Comment by thibaultCha** [comment]
Sounds good otherwise. But it's exactly the same as #100 and #101, you could have won 5 hours of your time lol

**Comment by thefosk** [comment]
Test don't pass because of a moonrocks problem, not code problem:

```
Error: Failed installing dependency: https://rocks.moonscript.org/cassandra-0.5-4.rockspec - Failed cloning git repository.
make: *** [install] Error 1
```

**Comment by thefosk** [comment]
Finally GitHub seems to work, tests pass.

**Comment by thibaultCha** [comment]
Copy-pasted from #100 since this PR was based on it:

Implementing #18 changes

- [x] rename `accounts` to `consumers`
- [x] rename `provider_id` to `custom_id`
- [ ] Rename `plugins` to `plugins_configurations` or something
- [ ] make username required for `consumers` #96
- [ ] Externalize plugins
  - [ ] Create tables for plugins which need some (keyauth, basicauth, ratelimiting)
  - [ ] and give them a migration feature
  - [ ] as well as DAO extensibility
  - [ ] API routes extensibility
- [ ] Remove `applications`

**Pull request merged**
