### PR TITLE
add the yaml load exception error info

### PR DESCRIPTION
**Pull request by ajayk**

### CODE REVIEW

**Comment by thefosk** [comment]
@ajayk can you describe what are you trying to do here?

**Comment by Tieske** [comment]
@thibaultCha This can also be closed in favour of the CLI and config refactor no?

**Comment by ajayk** [comment]
@thefosk this was added as a followup for #985 #949

**Comment by thefosk** [comment]
Closing this as not more relevant since `refactor/cli` changes how the configuration is parsed.

**Pull request closed without merging**
