### PR TITLE
Refactored tests for the request transformer plugin

### PR DESCRIPTION
**Pull request by Tieske**
Includes a bugfix and some helper updates.

### CODE REVIEW

**Comment by Tieske** [comment]
@thibaultCha I reworked descriptions etc. according to comments elsewhere. Please review

**Comment by thibaultCha** [comment]
Looks good except for a few things:
- would you please rename the tests files so that they are ordered by atomicity. `01-***_spec.lua`, `02-***_spec.lua`. Here the access tests should probably run before the long bodies tests etc...
- squash your commits and properly prefix/name your final commit like all other commits (`tests(req-transformer) refactor + new testing tools`)
- use `assert.is_nil` and `assert.equals` over `assert.is.Nil` and `assert.are.equal` for the sake of consistency and brevity.

Finally, I think we should merge #1322 first, and remove the new helpers included in this changelog.

**Comment by thefosk** [comment]
I really need the multipart upload

**Comment by thibaultCha** [comment]
Already raised my concerns, waiting for an update on this one.

**Pull request merged**
