### PR TITLE
feat(plugins) new Galileo plugin

### PR DESCRIPTION
**Pull request by thibaultCha**
- Implement the ALF 1.1 specs from https://github.com/Mashape/api-log-format
- Implement the latest Galileo agents specs from https://github.com/Mashape/galileo-agent-spec
- Rename the plugin from `mashape-analytics` to `galileo`. This still requires more testing than I did so far
- It has more tests than the old plugin, and should perform better.

Still waiting on https://github.com/openresty/lua-cjson/pull/6 to make it to an OpenResty release, until then, this still uses a workaround to serialize empty table to empty JSON arrays.

Goes with https://github.com/Mashape/getkong.org/pull/214 for the updated documentation.

### CODE REVIEW

**Comment by thefosk** [comment]
As a reminder, if the target port is `443` this plugin should be able to handle HTTPs.

**Comment by thibaultCha** [comment]
Perfectly aware. Still waiting on Galileo v3 running in prod with SSL support.

**Comment by thefosk** [comment]
By the way I think the protocol should be specified in a separate property. I could have Galileo running on-prem on an arbitrary HTTPs port, like `9000`, or running on port `443` but under HTTP.

**Comment by thibaultCha** [comment]
Also aware, also planning on doing it once Galileo v3 is released.

**Pull request closed without merging**
