### PR TITLE
Document/readme

### PR DESCRIPTION
**Pull request by montanaflynn**
Made some changes to the README, as can you can [see here](https://github.com/Mashape/kong/tree/document/readme):

- Added community channels to top
- Put documentation link as first section
- Included features and benefits

### CODE REVIEW

**Comment by thibaultCha** [comment]
Like Neo in the matrix, really...?

**Comment by montanaflynn** [comment]
Before Kong:


After Kong:

**Comment by montanaflynn** [comment]
Really though, if you don't like it please suggest the replacement text. I also need to add benchmark section before being this should be merged.

**Comment by Nijikokun** [comment]
If you're going to use the analogy, Neo should be uppercased.

**Comment by thibaultCha** [comment]
"Control your Kong cluster from the command line". But it's also lie, the CLI only controls a node

**Comment by montanaflynn** [comment]
You can control your kong cluster with the CLI one node at a time or all at once with bash or tools like https://github.com/duncs/clusterssh. Hopefully the CLI will be able to control the cluster in the future.

**Comment by thibaultCha** [comment]
Hopefully

**Pull request merged**
