### PR TITLE
Replace the shelled out openssl pem to der conversion,  in favor of l…

### PR DESCRIPTION
**Pull request by cleblanc87**
…ua-resty-core conversion method cert_pem_to_der, this will now preserve the full certificate chain

### CODE REVIEW

**Comment by cleblanc87** [comment]
Fixes #872.

Started in on adding tests, but importing "ngx.ssl" breaks the tests with
`/usr/local/share/lua/5.1/ngx/ssl.lua:5: module 'resty.core.base' not found:No LuaRocks module found for resty.core.base`

I am not too familiar with this ecosystem, so a nudge in the right direction would be very welcome :)

**Comment by thibaultCha** [comment]
This error occurs because in `spec/plugins/ssl/access_spec.lua`, the `kong.plugins.ssl.ssl_util` module is being unit tested, so it is required [here](https://github.com/Mashape/kong/blob/master/spec/plugins/ssl/access_spec.lua#L2). Because this does not run inside Nginx, `resty.core.base` is not in the `LUA_PATH`.

iirc, this is the reason why the module is required inside the functions, such as [here](https://github.com/Mashape/kong/blob/master/kong/plugins/ssl/certificate.lua#L6), so they can be required while unit testing. I am not a fan of this solution, I think a patch that properly requires `ngx.ssl` at module-level for this plugin (and removing the unit tests in `access_spec.lua`) would be an improvement.  Do you want some time to update yours?

**Comment by thefosk** [comment]
Looking forward to see a test for this, so we can close the issue.

**Comment by thefosk** [comment]
By the way it seems like the new version of OpenResty is also going to ship with [`priv_key_pem_to_der`](https://github.com/openresty/lua-nginx-module/pull/637/files#diff-7af443febbb8b9397095e012f6a93fa2R891) which will allow us to never use OpenSSL for both conversions (key/cert to DER).

**Comment by thefosk** [comment]
Fixed with #968.

**Pull request closed without merging**
