### PR TITLE
[config] put `cache` in the DAO config.

### PR DESCRIPTION
**Pull request by thibaultCha**
This makes it clearer for users that we are here talking about the cache
of the database entities, and not of any API added to Kong. It also
merges properties that are very linked together. In the case of another
database, one might want to have a bigger, or smaller caching value.

### CODE REVIEW

**Comment by thibaultCha** [comment]
@thefosk Please thoughts, this makes the config less confusing for users I believe, as documented in: Mashape/getkong.org#45

**Comment by thefosk** [comment]
I don't mind renaming it to `database_cache`, but it shouldn't be inside of the Cassandra-specific configuration because the database cache is DAO agnostic. I don't agree with this change: https://github.com/Mashape/kong/pull/162/files#diff-e19a50844f2b535a0140d2ce8281574aR66

**Comment by thibaultCha** [comment]
Like explained, you might want to give a different cache value for cassandra than for sqlite.

**Comment by thefosk** [comment]
I still think caching should be DAO agnostic, until it will be removed when #15 is fully implemented. 

The only reason why the cache should be different for different DAOs is if there are some performance issues when setting different expirations times, which is not going to be the case (and we shouldn't support any datastore where this might be a case). 

Moreover the cache expiration is not related to the datastore but related to the a shared dictionary inside nginx, items don't expire from the datastore but from a shared dictionary. Putting the cache inside the datastore properties makes it seem like it's a cache that's somehow related to the datastore items/tables (like https://dev.mysql.com/doc/refman/5.1/en/query-cache.html).

**Comment by thibaultCha** [comment]
@thefosk updated

**Comment by thefosk** [comment]
It seems like now it's in two places, you forgot to delete the conf entry in the datastore settings.

**Comment by thibaultCha** [comment]
Oops yes, fixed. Waiting for tests and I'll merge.

**Pull request merged**
