### PR TITLE
Add Authorization header if userinfo is present

### PR DESCRIPTION
**Pull request by amir**
### Summary

Add Authorization header if userinfo is present
### Full changelog
- Add Basic Authorization to http-log plugin

### CODE REVIEW

**Comment by amir** [comment]
Added tests and fixed indentation. CI failure doesn't seem to be related to the changes though.

**Comment by Tieske** [comment]
@thefosk do we really want to log secrets?

**Comment by p0pr0ck5** [comment]
@amir can you rebase this against `next` to resolve the merge conflict?

**Comment by Tieske** [comment]
merged through #2432. Thanks for your contribution @amir 👍

**Pull request closed without merging**
