### PR TITLE
docs(readme) fix test omission

### PR DESCRIPTION
**Pull request by WALL-E**
test-all = unit + integration + plugins

> Makefile
```
test:
	@$(TEST_CMD) spec/01-unit

test-integration:
	@$(TEST_CMD) spec/02-integration

test-plugins:
	@$(TEST_CMD) spec/03-plugins

test-all:
	@$(TEST_CMD) spec/
```

### CODE REVIEW

**Comment by WALL-E** [comment]
sorry, select a error branch

**Comment by Tieske** [comment]
This is the correct branch for fixes

**Comment by Tieske** [comment]
@WALL-E can you just updates the commit message? "docs(readme) fix test omission"

**Comment by WALL-E** [comment]
@Tieske I updated it

**Comment by thibaultcha** [comment]
Thank you.

**Pull request merged**
