### PR TITLE
Add Konga in community tools

### PR DESCRIPTION
**Pull request by pantsel**
Just a simple addition to README.md

### CODE REVIEW

**Comment by thibaultcha** [comment]
Hi,

Thanks for the addition; unfortunately we won't be adding new UI tools in there anymore. In the future, this section will be revamped. Sorry.

**Comment by harryparmar** [comment]
@thibaultcha IMHO Konga is one of the best third party tools supporting Kong at the moment, and it gets better it is open source. It is complete admin tool with ability to take snapshots and restore this snapshot to any node of your choosing. Also person can import/export this snapshot as JSON file. New version adds health checks to nodes and apis with email notifications or endpoints of your choosing. It has more features than of couple of tools out there combined together like Kong Dashboard, Kongfig etc and does better job than them in each area , sort of Master of ALL. and it adds health check to top it all. All of this packaged in best GUI which is very clean and intuitive. @pantsel  Kong's readme already mentions Konga, your request was duplicating entry.

**Comment by harryparmar** [comment]
@thibaultcha I want to add...several of those tools mentioned in community section have not been updated in last two years. Konga is active project supporting latest 0.10.x and @pantsel responds to all requests immediately and actively looks for  feedback, if anything Konga should be prominently placed in the community section.

**Comment by harryparmar** [comment]
@thibaultcha nevermind I realized Konga tool that's mentioned is different tool so pantsel's Konga definitely needs to be on the list

**Comment by sashahilton00** [comment]
@thibaultcha glad to hear that it is getting a revamp, does that mean the documentation is going to be reviewed and cleared up in the not too distant future? In the meantime, would it possible to include Konga? It is a great management interface, and a little exposure on Kong's repo would help encourage development I'm sure...

**Pull request closed without merging**
