### PR TITLE
fix(logging) include 'balancer_by_lua' latency in Kong latency

### PR DESCRIPTION
**Pull request by thefosk**
* fix(logging) include `balancer_by_lua` latency in Kong latency

### CODE REVIEW

**Comment by p0pr0ck5** [comment]
@thefosk do we still need this, or can we close this PR since we have a few debug/latency patches floating around?

**Comment by thibaultcha** [comment]
We still need this, as this is missing from the current logging serializers, but as mentioned, a better version of it.

**Comment by thefosk** [comment]
I will give this another look soon

**Comment by Tieske** [comment]
you can use the `tries` field as it will contain info for each try (will be logged by serializers). See https://github.com/Mashape/kong/blob/master/kong/core/handler.lua#L108

As a side note: on its own the latency here will pretty much always be near 0ms, as the actual dns resolution is done in the `access` phase.

**Comment by thibaultcha** [comment]
(cc @thefosk)

**Comment by Tieske** [comment]
@thibaultcha @thefosk I updated this pr to properly track time spent per try. Please have a look.

**Comment by thibaultcha** [comment]
This one will do. Updated the commit author + moved the balancer callbacks to the right place in `core.handler` (after `access`). Thanks!

**Pull request merged**
