### PR TITLE
[feature] Admin API now supports form-encoded and json

### PR DESCRIPTION
**Pull request by thibaultCha**
- [x] Admin API accepts both form-encoded and JSON parameters. `parse_params()` is a custom Lapis helper which parses form-encoded or application/json parameters. If sending form-encoded, it will un-nest keys like `value.object=123` to `{value={object=123}}`
- [x] Fix a bug in the schema validation. If a field had more than 1 rule, it would only validate one of them.
- [x] Fix Lapis's parsing behaviour with params such as `?key[1]=val` being parsed as `{["1"]="val"}`. it is now properly parsed as `{"val"}`
- [x] Fix more bugs related with the DAO
- [x] Refactored a lot of code, considerably reducing LOCs
- [x] A lot more tests for the Admin API
- [x] Change current PUT to be PATCH (current PUT behaves like PATCH)
- [x] Implement real PUT

We can now query the Admin API with form-encoded params or a JSON body assuming the content type contains `application/json`. Malformed JSON will return a 400.

Most of the new LOCs are tests, otherwise the actual number of LOCs is considerably reduced.

Hold on before merging, this maybe needs a bit more testing but opening to allow discussion.

### CODE REVIEW

**Comment by ahmadnassri** [comment]
> We can now query the Admin API with form-encoded params or a JSON body

amazing! been waiting for this! good work! :clap:

this will also make the documentation so much cleaner!

**Comment by sinzone** [comment]
@ahmadnassri @Nijikokun  who updates the doc?

**Comment by thibaultCha** [comment]
We'll do it when finished and merged

**Comment by thibaultCha** [comment]
Okay, this PR also converts our current PUT to being PATCH (that's what it was) and support for real PUT: create like POST if doesn't exist, update if a full body is given, (that is with an `id`, currently).

**Pull request merged**
