### PR TITLE
Small spelling changes in Docs

### PR DESCRIPTION
**Pull request by ChristopherBiscardi**
Was reading through the docs and ran across these.

### CODE REVIEW

**Comment by thibaultCha** [comment]
Ha! That would be me... Thank you!

**Comment by sinzone** [comment]
@ChristopherBiscardi small unrelated question. as long as we follow guidelines, every image can become an official docker image or you need some big numbers upfront?

**Comment by ChristopherBiscardi** [comment]
@sinzone Just follow the guidelines here: https://github.com/docker-library/official-images and submit the PR. Being upstream and the fact that [docker-kong](https://github.com/Mashape/docker-kong) already exists (and looks maintained) is a strong + toward getting it merged.

**Comment by sinzone** [comment]
@ChristopherBiscardi thanks.

**Pull request merged**
