### PR TITLE
Add support for oauth2 plugin X-Forwarded-Proto HTTPS override

### PR DESCRIPTION
**Pull request by CyExy**
We have an SSL wrapper and load balancer in front of kong so it would be unnecessary to wrap it just for kong.

> "a de facto standard for identifying the originating protocol of an HTTP request, since a reverse proxy (load balancer) may communicate with a web server using HTTP even if the request to the reverse proxy is HTTPS ..."

source https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Common_non-standard_request_fields

### CODE REVIEW

**Comment by CyExy** [comment]
Not sure why the CI failed, runned `make test-all` locally and all of the test pass.

**Comment by thefosk** [comment]
@CyExy Looks good to me. Can you submit the PR against the `next` branch?

Tests are failing because of a problem we currently have with our CI systems, but if it works locally it's good.

**Comment by CyExy** [comment]
@thefosk hoped to sneak the fix in as a hot fix :) but if you would prefer to release it `next` I can rebase against `next` branch in a new PR.

**Comment by thibaultCha** [comment]
Thanks! We are going to release a patch version for this and #644.

**Comment by CyExy** [comment]
Thank you very much!

**Pull request merged**
