### PR TITLE
Feature/cache

### PR DESCRIPTION
**Pull request by thefosk**
This pull request is the first step in implementing #15, with the final step being having an invalidation system in place.

It implements a time-expiration caching system configurable through `kong.yaml` configuration file.

```yaml
# Cache configuration
cache:
  expiration: 5 # In seconds
```

I'm creating the pull request without merging, and will post the results of the benchmark below.

### CODE REVIEW

**Comment by thefosk** [comment]
# Benchmarks

The benchmarks have been executed on the EC2 environment, using:

```
siege -c 300 -t 60S ...
```

### Without cache (version `0.0.1-beta`)

```
Transactions:          70626 hits
Availability:          98.53 %
Elapsed time:          21.80 secs
Data transferred:         0.88 MB
Response time:            0.09 secs
Transaction rate:      3239.72 trans/sec
Throughput:           0.04 MB/sec
Concurrency:          297.06
Successful transactions:       70626
Failed transactions:          1052
Longest transaction:          1.37
Shortest transaction:         0.01
```

### With cache (default=5s)

```
Transactions:         535318 hits
Availability:          99.77 %
Elapsed time:          43.45 secs
Data transferred:         6.64 MB
Response time:            0.02 secs
Transaction rate:     12320.32 trans/sec
Throughput:           0.15 MB/sec
Concurrency:          295.57
Successful transactions:      535318
Failed transactions:          1209
Longest transaction:          5.02
Shortest transaction:         0.00
```

**Comment by thibaultCha** [comment]
nice

**Comment by samek** [comment]
Is this already in the 0.4.1 ?

**Comment by thibaultCha** [comment]
This is in Kong since the first release.

**Comment by thefosk** [comment]
@samek bear in mind that is the internal cache of Kong for its internal entities, not an HTTP caching layer for the upstream APIs.

**Comment by samek** [comment]
@thefosk  exactly what I thought it was for (http upstream). :( 

Any plans for that ?

**Comment by mashapedeployment** [comment]
@samek https://github.com/Mashape/kong/issues?q=caching+is%3Aissue

**Comment by samek** [comment]
ok in the mean time I've added it to the nginx config in kong.yml  - for docker. 
If someone want's to try (it'll be caching all apis's). 

Add parts between the ##CUSTOM CACHING##

     --- a/config.docker/kong.yml
     +++ b/config.docker/kong.yml
     @@ -35,7 +35,8 @@ database: cassandra
      databases_available:
        cassandra:
          properties:
     -      hosts: "cassandra"
     +      hosts: 
     +CASSANDRAHOSTS
            port: 9042
            timeout: 1000
            keyspace: kong
     @@ -124,8 +125,13 @@ nginx: |
          ';
      
          init_worker_by_lua 'kong.exec_plugins_init_worker()';
     +    ##CUSTOM CACHING##
     +    proxy_cache_path  /tmp/ levels=1 keys_zone=apicache:10m;
     +    ##CUSTOM CACHING##
 
          server {
     +      set_real_ip_from 0.0.0.0/0;
     +      real_ip_header Cres-Client-IP;
            server_name _;
            listen {{proxy_port}};
            listen {{proxy_ssl_port}} ssl;
     @@ -144,6 +150,15 @@ nginx: |
              # Authenticate the user and load the API info
              access_by_lua 'kong.exec_plugins_access()';
      
     +        ##CUSTOM CACHING##
     +        proxy_cache apicache;
     +        proxy_cache_use_stale updating;
     +        proxy_cache_lock on;
     +        proxy_cache_valid 200 10s;
     +        proxy_ignore_headers X-Accel-Expires Expires Cache-Control;
     +        add_header X-Proxy-Cache $upstream_cache_status;
     +        ##CUSTOM CACHING##
     +
              # Proxy the request
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
     @@ -203,4 +218,4 @@ nginx: |
            # Do not remove, additional configuration placeholder for some plugins
            # {{additional_configuration}}
          }

**Comment by samek** [comment]
Btw. Looks like analitics only counts misses.

**Pull request merged**
