### PR TITLE
task(rate-limiting) Allow connecting to non-zero Redis databases (#17…

### LINKED ISSUE #1726: Connect to non-zero Redis databases
### Summary

Some plugins (request/response rate limits) can use Redis as an external fast persistent storage. To connect to Redis, the parameters are host, port and password (optional). It's not possible to select a non-zero database in Redis. As result, it's not possible to share an existing Redis deployment if the zero database is already in use. 

I suggest to add a new parameter with the cardinal of the database in Redis, being zero by default. The resyt-redis author suggest to implement this feature as follows: https://github.com/openresty/lua-resty-redis/issues/53
### Steps To Reproduce
1. Configure a rate-limiting plugin to connect to an existing Redis database with zero database in use.
2. Both data sets will be stored in the same database.
3. There is a chance of data corruption.

### PR DESCRIPTION
**Pull request by diegoparrilla**
**Note: new features are to be opened against next, hotfixes against master.**

### Summary

Rate limiting now supports non-zero redis database. 
Keep alived Redis connections were not working. Now they work, increasing the performance of the service.

### Full changelog

* Modified plugin unit tests to support non-zero databases.
* Modified plugin to work with short lived http connections 

### Issues resolved

Fix #1726

### CODE REVIEW

**Comment by thefosk** [comment]
@diegoparrilla thank you - could you also implement the same changes to the response rate-limiting plugin? The changes would be very similar if not almost identical.

**Comment by thefosk** [comment]
Closed with #1941.

**Comment by varuns11** [comment]
I don't see this change in 0.11.0 version. Why is this not included? And how could we utilise the redis pool without this change?

**Comment by thibaultcha** [comment]
This is included in 0.11.0: https://github.com/Mashape/kong/blob/0.11.0/kong/plugins/rate-limiting/schema.lua#L20

**Pull request closed without merging**
